// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.repository;

import com.purely.wishlist.model.ShareToken;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;

/**
 * MongoDB repository for {@link ShareToken} documents.
 *
 * <p>Provides lookup by share token string for resolving shared wishlist links.</p>
 */
public interface ShareTokenRepository extends MongoRepository<ShareToken, String> {

    Optional<ShareToken> findByToken(String token);

    Optional<ShareToken> findByUserId(String userId);

}
