// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.repository;

import com.purely.wishlist.model.ShareToken;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;

/**
 * MongoDB repository for {@link ShareToken} documents.
 *
 * <p>Provides lookup by share token string for resolving shared wishlist links.</p>
 */
public interface ShareTokenRepository extends MongoRepository<ShareToken, String> {

    /**
     * Find a share token document by its token string.
     *
     * @param token the UUID share token
     * @return an Optional containing the share token if it exists
     */
    Optional<ShareToken> findByToken(String token);

    /**
     * Find a share token document by the owning user's identifier.
     *
     * @param userId the owner's user identifier
     * @return an Optional containing the share token if one exists for this user
     */
    Optional<ShareToken> findByUserId(String userId);

}
