// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.repository;

import com.purely.wishlist.model.WishlistItem;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.List;
import java.util.Optional;

/**
 * MongoDB repository for {@link WishlistItem} documents.
 *
 * <p>Provides CRUD operations and custom finder methods for querying
 * wishlist items by user and product identifiers.</p>
 */
public interface WishlistRepository extends MongoRepository<WishlistItem, String> {

    /**
     * Retrieve all wishlist items belonging to a specific user.
     *
     * @param userId the owner's user identifier
     * @return list of wishlist items, possibly empty
     */
    List<WishlistItem> findByUserId(String userId);

    /**
     * Find a specific wishlist entry for a user-product combination.
     *
     * @param userId    the owner's user identifier
     * @param productId the product identifier
     * @return an Optional containing the item if it exists
     */
    Optional<WishlistItem> findByUserIdAndProductId(String userId, String productId);

    /**
     * Check whether a user already has a specific product in their wishlist.
     *
     * @param userId    the owner's user identifier
     * @param productId the product identifier
     * @return true if the combination exists
     */
    boolean existsByUserIdAndProductId(String userId, String productId);

    /**
     * Delete a wishlist entry by user and product identifiers.
     *
     * @param userId    the owner's user identifier
     * @param productId the product identifier
     */
    void deleteByUserIdAndProductId(String userId, String productId);

    /**
     * Count the number of wishlist items for a specific user.
     *
     * @param userId the owner's user identifier
     * @return the count of wishlist items
     */
    long countByUserId(String userId);

}
