// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.repository;

import com.purely.wishlist.model.WishlistItem;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.List;
import java.util.Optional;

/**
 * MongoDB repository for {@link WishlistItem} documents.
 *
 * <p>Provides CRUD operations and custom finder methods for querying
 * wishlist items by user and product identifiers.</p>
 */
public interface WishlistRepository extends MongoRepository<WishlistItem, String> {

    List<WishlistItem> findByUserId(String userId);

    Optional<WishlistItem> findByUserIdAndProductId(String userId, String productId);

    boolean existsByUserIdAndProductId(String userId, String productId);

    void deleteByUserIdAndProductId(String userId, String productId);

    long countByUserId(String userId);

}
