// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/__tests__/setup.js',
    css: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'json-summary'],
      include: [
        'src/api-service/cart.service.jsx',
        'src/components/cart/cart.jsx',
        'src/pages/checkout/checkout.jsx',
        'src/pages/products/products.jsx',
      ],
    },
  },
  define: {
    'process.env': {
      VITE_API_BASE_URL: JSON.stringify('http://localhost:8080'),
    },
  },
})
