// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request body for adding a product to the wishlist.
 *
 * <p>The {@code productId} is validated at the controller boundary
 * via Bean Validation ({@code @NotBlank}) before reaching the service layer.</p>
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AddToWishlistRequest {

    /** Product identifier to add to the wishlist. Must not be null or blank. */
    @NotBlank(message = "Product ID is required")
    private String productId;

}
