// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Response DTO representing a single wishlist item with enriched product details.
 *
 * <p>Product details (name, image URL, price, availability) are resolved
 * at query time via the product-service OpenFeign client. If product-service
 * is unavailable, the item is flagged as {@code available = false}.</p>
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class WishlistItemResponse {

    /** Product identifier. */
    private String productId;

    /** Product display name (resolved from product-service). */
    private String productName;

    /** Product image URL (resolved from product-service). */
    private String imageUrl;

    /** Product price (resolved from product-service). */
    private double price;

    /** Whether the product is currently available. False if product-service is unreachable. */
    private boolean available;

    /** Timestamp when the product was added to the wishlist. */
    private LocalDateTime addedAt;

}
