spring:
    application:
        name: cart-service
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/purely_cart_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9060

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
