// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useContext, useState } from "react";
import { RiDeleteBin6Line } from "react-icons/ri";
import { AiOutlineShoppingCart } from "react-icons/ai";
import WishlistContext from "../../contexts/wishlist.context";
import CartContext from "../../contexts/cart.context";
import Loading from "../loading/loading";
import { PLACEHOLDER_IMAGE } from "../../constants/images";
import "./WishlistCard.css";

function WishlistCard({ item, readOnly = false }) {
  const { removeFromWishlist, moveToCart } = useContext(WishlistContext);
  const { addItemToCart } = useContext(CartContext);
  const [isMoving, setIsMoving] = useState(false);

  const handleRemove = async () => {
    await removeFromWishlist(item.productId);
  };

  const handleMoveToCart = async () => {
    setIsMoving(true);
    try {
      if (moveToCart) {
        await moveToCart(item.productId);
      } else {
        await addItemToCart(item.productId, 1);
        await removeFromWishlist(item.productId);
      }
    } catch {
      await addItemToCart(item.productId, 1);
      await removeFromWishlist(item.productId);
    }
    setIsMoving(false);
  };

  return (
    <div className="wishlist-card">
      <img
        src={item.imageUrl}
        alt={item.productName}
        className="wishlist-card__image"
        onError={(e) => {
          if (!e.target.dataset.fallback) {
            e.target.dataset.fallback = "true";
            e.target.src = PLACEHOLDER_IMAGE;
          }
        }}
      />

      <div className="wishlist-card__info">
        <h4 className="wishlist-card__name">{item.productName}</h4>
        <span className="wishlist-card__price">
          Rs. {parseFloat(item.price || 0).toFixed(2)}
        </span>
        <span
          className={`wishlist-card__availability ${item.available ? "in-stock" : "out-of-stock"}`}
        >
          {item.available ? "In Stock" : "Out of Stock"}
        </span>
      </div>

      {!readOnly && (
        <div className="wishlist-card__actions">
          {isMoving ? (
            <Loading />
          ) : (
            <>
              <button
                className="wishlist-card__btn wishlist-card__btn--cart"
                onClick={handleMoveToCart}
                disabled={!item.available}
                title={item.available ? "Move to cart" : "Currently unavailable"}
              >
                <AiOutlineShoppingCart size={18} />
                <span>Move to Cart</span>
              </button>
              <button
                className="wishlist-card__btn wishlist-card__btn--remove"
                onClick={handleRemove}
                title="Remove from wishlist"
              >
                <RiDeleteBin6Line size={18} />
                <span>Remove</span>
              </button>
            </>
          )}
        </div>
      )}
    </div>
  );
}

export default WishlistCard;
