// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AiOutlineHeart, AiFillHeart } from "react-icons/ai";
import WishlistContext from "../../contexts/wishlist.context";
import { AuthContext } from "../../contexts/auth.context";
import "./WishlistButton.css";

function WishlistButton({ productId, className = "", size = 22 }) {
  const { addToWishlist, removeFromWishlist, isInWishlist } =
    useContext(WishlistContext);
  const { user } = useContext(AuthContext);
  const navigate = useNavigate();
  const [animating, setAnimating] = useState(false);

  const wishlisted = isInWishlist(productId);

  const handleToggle = async (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (!user) {
      navigate("/auth/login");
      return;
    }

    setAnimating(true);
    setTimeout(() => setAnimating(false), 300);

    if (wishlisted) {
      await removeFromWishlist(productId);
    } else {
      await addToWishlist(productId);
    }
  };

  return (
    <button
      className={`wishlist-btn ${wishlisted ? "wishlisted" : ""} ${animating ? "wishlist-btn--pop" : ""} ${className}`}
      onClick={handleToggle}
      aria-label={wishlisted ? "Remove from wishlist" : "Add to wishlist"}
      title={wishlisted ? "Remove from wishlist" : "Add to wishlist"}
      type="button"
    >
      {wishlisted ? (
        <AiFillHeart size={size} className="wishlist-btn__icon wishlist-btn__icon--filled" />
      ) : (
        <AiOutlineHeart size={size} className="wishlist-btn__icon" />
      )}
    </button>
  );
}

export default WishlistButton;
