// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useContext } from "react";
import { AiOutlineHeart } from "react-icons/ai";
import { Link } from "react-router-dom";
import WishlistContext from "../../contexts/wishlist.context";
import "./WishlistBadge.css";

function WishlistBadge() {
  const { wishlistItems } = useContext(WishlistContext);
  const count = wishlistItems?.length || 0;

  return (
    <Link to="/wishlist" className="wishlist-badge" aria-label="View wishlist">
      <AiOutlineHeart size={22} className="wishlist-badge__icon" />
      <span className="wishlist-badge__count">({count})</span>
    </Link>
  );
}

export default WishlistBadge;
