// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.openfeign.EnableFeignClients;

/**
 * Entry point for the Wishlist microservice.
 *
 * <p>Registers with Eureka for service discovery and enables OpenFeign
 * declarative REST clients for inter-service communication with
 * product-service and cart-service.</p>
 */
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
public class WishlistServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(WishlistServiceApplication.class, args);
    }

}
