spring:
    application:
        name: order-service
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/purely_order_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9070

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
