// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.controller;

import com.purely.wishlist.dto.AddToWishlistRequest;
import com.purely.wishlist.dto.ApiResponseDto;
import com.purely.wishlist.service.WishlistService;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/wishlist")
@Slf4j
public class WishlistController {

    @Autowired
    private WishlistService wishlistService;

    @PostMapping("/add")
    public ResponseEntity<ApiResponseDto<?>> addToWishlist(
            @RequestHeader("X-User-Id") String userId,
            @Valid @RequestBody AddToWishlistRequest request) {
        log.info("POST /wishlist/add - userId={}, productId={}", userId, request.getProductId());
        return wishlistService.addToWishlist(userId, request.getProductId());
    }

    @DeleteMapping("/remove/{productId}")
    public ResponseEntity<ApiResponseDto<?>> removeFromWishlist(
            @RequestHeader("X-User-Id") String userId,
            @PathVariable String productId) {
        log.info("DELETE /wishlist/remove/{} - userId={}", productId, userId);
        return wishlistService.removeFromWishlist(userId, productId);
    }

    @GetMapping("/get/byUser")
    public ResponseEntity<ApiResponseDto<?>> getWishlistItems(
            @RequestHeader("X-User-Id") String userId) {
        log.info("GET /wishlist/get/byUser - userId={}", userId);
        return wishlistService.getWishlistItems(userId);
    }

    @PostMapping("/moveToCart/{productId}")
    public ResponseEntity<ApiResponseDto<?>> moveToCart(
            @RequestHeader("X-User-Id") String userId,
            @PathVariable String productId) {
        log.info("POST /wishlist/moveToCart/{} - userId={}", productId, userId);
        return wishlistService.moveToCart(userId, productId);
    }

    @PostMapping("/share")
    public ResponseEntity<ApiResponseDto<?>> shareWishlist(
            @RequestHeader("X-User-Id") String userId) {
        log.info("POST /wishlist/share - userId={}", userId);
        return wishlistService.shareWishlist(userId);
    }

    @GetMapping("/shared/{shareToken}")
    public ResponseEntity<ApiResponseDto<?>> getSharedWishlist(
            @PathVariable String shareToken) {
        log.info("GET /wishlist/shared/{}", shareToken);
        return wishlistService.getSharedWishlist(shareToken);
    }

}
