// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
// Covers: US-002 (PURELY-17) — Initialize Cart State with Safe Defaults
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { renderHook, waitFor } from '@testing-library/react'
import axios from 'axios'

vi.mock('axios')

describe('CartService — safe default state (US-002 / PURELY-17)', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    localStorage.setItem('user', JSON.stringify({ type: 'Bearer ', token: 'test-token' }))
  })

  afterEach(() => {
    localStorage.clear()
  })

  it('initial cart state has safe numeric defaults (subtotal=0, noOfCartItems=0)', async () => {
    axios.get.mockResolvedValueOnce({
      data: { response: { cartItems: [], subtotal: 0, noOfCartItems: 0 } },
    })

    const { default: CartService } = await import('../api-service/cart.service.jsx')
    const { result } = renderHook(() => CartService())

    expect(result.current.cart.subtotal).toBe(0)
    expect(result.current.cart.noOfCartItems).toBe(0)
    expect(Array.isArray(result.current.cart.cartItems)).toBe(true)
    expect(result.current.cart.cartItems.length).toBe(0)
  })

  it('parseFloat with || 0 guard produces "0.00" for all falsy inputs', () => {
    // This validates the exact pattern used in cart.jsx and checkout.jsx:
    //   parseFloat(cartItem.amount || 0).toFixed(2)
    expect(parseFloat(undefined || 0).toFixed(2)).toBe('0.00')
    expect(parseFloat(null || 0).toFixed(2)).toBe('0.00')
    expect(parseFloat(0 || 0).toFixed(2)).toBe('0.00')
    expect(parseFloat('' || 0).toFixed(2)).toBe('0.00')
    expect(parseFloat(false || 0).toFixed(2)).toBe('0.00')

    // Valid numbers pass through correctly
    expect(parseFloat(42.5 || 0).toFixed(2)).toBe('42.50')
    expect(parseFloat(100 || 0).toFixed(2)).toBe('100.00')
  })

  it('error handler resets cart to safe defaults (US-002)', async () => {
    axios.get.mockRejectedValueOnce(new Error('Network Error'))

    const { default: CartService } = await import('../api-service/cart.service.jsx')
    const { result } = renderHook(() => CartService())

    await waitFor(() => {
      expect(result.current.cartError).toBe(true)
    })

    expect(result.current.cart.subtotal).toBe(0)
    expect(result.current.cart.noOfCartItems).toBe(0)
    expect(result.current.cart.cartItems).toEqual([])
  })

  it('cart resets to safe defaults when user has no token', async () => {
    localStorage.setItem('user', JSON.stringify({ type: 'Bearer ', token: null }))

    const { default: CartService } = await import('../api-service/cart.service.jsx')
    const { result } = renderHook(() => CartService())

    await waitFor(() => {
      expect(result.current.isProcessingCart).toBe(false)
    })

    expect(result.current.cart.subtotal).toBe(0)
    expect(result.current.cart.noOfCartItems).toBe(0)
    expect(result.current.cart.cartItems).toEqual([])
    expect(result.current.cartError).toBe(false)
  })
})
