// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
// Covers: US-003 (PURELY-18) — Safe Numeric Formatting in Cart Component
// Covers: US-005 (PURELY-20) — Image Fallback in Cart Component
import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import CartContext from '../contexts/cart.context'
import { AuthContext } from '../contexts/auth.context'
import Cart from '../components/cart/cart.jsx'

vi.mock('react-icons/ai', () => ({
  AiOutlineClose: () => <span data-testid="icon-close">X</span>,
  AiOutlinePlus: () => <span data-testid="icon-plus">+</span>,
  AiOutlineMinus: () => <span data-testid="icon-minus">-</span>,
}))
vi.mock('react-icons/ri', () => ({
  RiDeleteBin6Line: () => <span data-testid="icon-delete">D</span>,
}))
vi.mock('../components/loading/loading', () => ({
  default: () => <div data-testid="loading">Loading</div>,
}))
vi.mock('../components/info/info', () => ({
  default: ({ message }) => <div data-testid="info">{message}</div>,
}))

const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'%3E%3Crect fill='%23f0f0f0' width='200' height='200'/%3E%3Ctext fill='%23999' font-family='Arial' font-size='14' text-anchor='middle' x='100' y='105'%3ENo Image%3C/text%3E%3C/svg%3E"

function renderCart(cartData, opts = {}) {
  const cartCtx = {
    cart: cartData,
    cartError: false,
    isProcessingCart: false,
    addItemToCart: vi.fn(),
    removeItemFromCart: vi.fn(),
    getCartInformation: vi.fn(),
    ...opts.cartOverrides,
  }
  const authCtx = {
    user: { type: 'Bearer ', token: 'tok' },
    toggleUser: vi.fn(),
    ...opts.authOverrides,
  }

  return render(
    <MemoryRouter>
      <AuthContext.Provider value={authCtx}>
        <CartContext.Provider value={cartCtx}>
          <Cart isCartOpen={true} onClose={vi.fn()} />
        </CartContext.Provider>
      </AuthContext.Provider>
    </MemoryRouter>
  )
}

describe('Cart — safe numeric formatting (US-003 / PURELY-18)', () => {
  it('renders "0.00" for amount and subtotal when cartItem.amount is undefined — no NaN', () => {
    renderCart({
      cartItems: [
        { productId: '1', productName: 'Widget', price: 10, quantity: 1, amount: undefined, imageUrl: '/img.png' },
      ],
      subtotal: undefined,
    })
    // Both the item amount and subtotal should show 0.00, not NaN
    const matches = screen.getAllByText(/0\.00/)
    expect(matches.length).toBeGreaterThanOrEqual(2)
    expect(screen.queryByText(/NaN/)).toBeNull()
  })

  it('renders "0.00" when cartItem.amount is null — no NaN', () => {
    renderCart({
      cartItems: [
        { productId: '2', productName: 'Gadget', price: 5, quantity: 2, amount: null, imageUrl: '/img.png' },
      ],
      subtotal: null,
    })
    const matches = screen.getAllByText(/0\.00/)
    expect(matches.length).toBeGreaterThanOrEqual(2)
    expect(screen.queryByText(/NaN/)).toBeNull()
  })

  it('renders correct amount when cartItem.amount is a valid number', () => {
    renderCart({
      cartItems: [
        { productId: '3', productName: 'Gizmo', price: 25, quantity: 2, amount: 50, imageUrl: '/img.png' },
      ],
      subtotal: 50,
    })
    const matches = screen.getAllByText(/50\.00/)
    expect(matches.length).toBeGreaterThanOrEqual(1)
    expect(screen.queryByText(/NaN/)).toBeNull()
  })

  it('renders info message when no cart items exist', () => {
    renderCart({ cartItems: null, subtotal: 0 })
    expect(screen.getByText('No items in your cart!')).toBeInTheDocument()
  })
})

describe('Cart — image fallback (US-005 / PURELY-20)', () => {
  it('sets placeholder image on error', () => {
    renderCart({
      cartItems: [
        { productId: '10', productName: 'Broken Img', price: 10, quantity: 1, amount: 10, imageUrl: 'http://bad.url/img.png' },
      ],
      subtotal: 10,
    })

    const img = screen.getByAltText('Broken Img')
    expect(img).toBeInTheDocument()

    fireEvent.error(img)

    expect(img.src).toBe(PLACEHOLDER_IMAGE)
    expect(img.dataset.fallback).toBe('true')
  })

  it('does NOT loop — second error keeps placeholder (data-fallback guard)', () => {
    renderCart({
      cartItems: [
        { productId: '11', productName: 'Double Err', price: 5, quantity: 1, amount: 5, imageUrl: 'http://bad.url/x.png' },
      ],
      subtotal: 5,
    })

    const img = screen.getByAltText('Double Err')
    fireEvent.error(img)
    const srcAfterFirst = img.src

    // Fire error again — src should not change (guard prevents infinite loop)
    fireEvent.error(img)
    expect(img.src).toBe(srcAfterFirst)
  })
})
