// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
// Covers: US-004 (PURELY-19) — Safe Numeric Formatting in Checkout Page
// Covers: US-006 (PURELY-21) — Image Fallback in Checkout Page
import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import CartContext from '../contexts/cart.context'
import { AuthContext } from '../contexts/auth.context'
import CheckoutForm from '../pages/checkout/checkout.jsx'

vi.mock('../components/logo/logo', () => ({
  default: () => <div data-testid="logo">Logo</div>,
}))
vi.mock('../components/footer/copyright', () => ({
  default: () => <div data-testid="copyright">©</div>,
}))
vi.mock('../api-service/order.service', () => ({
  default: () => ({
    isLoading: false,
    error: null,
    placeOrder: vi.fn(),
  }),
}))

const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'%3E%3Crect fill='%23f0f0f0' width='200' height='200'/%3E%3Ctext fill='%23999' font-family='Arial' font-size='14' text-anchor='middle' x='100' y='105'%3ENo Image%3C/text%3E%3C/svg%3E"

function renderCheckout(cartData) {
  return render(
    <MemoryRouter>
      <AuthContext.Provider value={{ user: { type: 'Bearer ', token: 'tok' }, toggleUser: vi.fn() }}>
        <CartContext.Provider value={{ cart: cartData }}>
          <CheckoutForm />
        </CartContext.Provider>
      </AuthContext.Provider>
    </MemoryRouter>
  )
}

describe('Checkout — safe numeric formatting (US-004 / PURELY-19)', () => {
  it('renders "0.00" when cartItem.amount is undefined — no NaN', () => {
    renderCheckout({
      cartItems: [
        { productId: '1', productName: 'Widget', price: 10, quantity: 1, amount: undefined, imageUrl: '/img.png' },
      ],
      subtotal: undefined,
    })
    const prices = screen.getAllByText(/0\.00/)
    expect(prices.length).toBeGreaterThanOrEqual(1)
    expect(screen.queryByText(/NaN/)).toBeNull()
  })

  it('renders "0.00" when cartItem.amount is null — no NaN', () => {
    renderCheckout({
      cartItems: [
        { productId: '2', productName: 'Gadget', price: 5, quantity: 2, amount: null, imageUrl: '/img.png' },
      ],
      subtotal: null,
    })
    const prices = screen.getAllByText(/0\.00/)
    expect(prices.length).toBeGreaterThanOrEqual(1)
    expect(screen.queryByText(/NaN/)).toBeNull()
  })

  it('renders correct amount when values are valid numbers', () => {
    renderCheckout({
      cartItems: [
        { productId: '3', productName: 'Gizmo', price: 25, quantity: 2, amount: 50, imageUrl: '/img.png' },
      ],
      subtotal: 50,
    })
    expect(screen.getAllByText(/50\.00/).length).toBeGreaterThan(0)
  })

  it('renders subtotal "0.00" with empty cart', () => {
    renderCheckout({ cartItems: [], subtotal: 0 })
    expect(screen.getByText(/Rs\.\s*0\.00/)).toBeInTheDocument()
  })
})

describe('Checkout — image fallback (US-006 / PURELY-21)', () => {
  it('sets placeholder image on error', () => {
    renderCheckout({
      cartItems: [
        { productId: '10', productName: 'Bad Image', price: 10, quantity: 1, amount: 10, imageUrl: 'http://broken/img.png' },
      ],
      subtotal: 10,
    })

    const img = screen.getByAltText('Bad Image')
    fireEvent.error(img)

    expect(img.src).toBe(PLACEHOLDER_IMAGE)
    expect(img.dataset.fallback).toBe('true')
  })

  it('does NOT loop — guard prevents double fallback', () => {
    renderCheckout({
      cartItems: [
        { productId: '11', productName: 'Loop Test', price: 5, quantity: 1, amount: 5, imageUrl: 'http://broken/x.png' },
      ],
      subtotal: 5,
    })

    const img = screen.getByAltText('Loop Test')
    fireEvent.error(img)
    const srcAfterFirst = img.src
    fireEvent.error(img)
    expect(img.src).toBe(srcAfterFirst)
  })
})
