// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
// Covers: US-007 (PURELY-22) — Image Fallback in Products Page
// Updated: CR-001 fix — added smoke-render test with real Products component
import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { PLACEHOLDER_IMAGE } from '../constants/images'

// Mock external dependencies for real Products component smoke test
vi.mock('../api-service/product.service', () => ({
  default: () => ({
    getAllCategories: vi.fn(),
    getAllProducts: vi.fn(),
    getProductsByCategory: vi.fn(),
    isLoading: false,
    categories: [],
    products: [
      { id: '1', productName: 'Test Product', price: 100, imageUrl: 'http://broken/img.png', description: 'desc' },
    ],
    error: false,
  }),
}))
vi.mock('../components/header/header', () => ({ default: () => <div data-testid="header" /> }))
vi.mock('../components/footer/footer', () => ({ default: () => <div data-testid="footer" /> }))
vi.mock('../components/loading/loading', () => ({ default: () => <div data-testid="loading" /> }))
vi.mock('../components/info/info', () => ({ default: () => <div data-testid="info" /> }))

// Use vi.hoisted so the context is available when vi.mock is hoisted
const { MockCartContext } = vi.hoisted(() => {
  const React = require('react')
  return { MockCartContext: React.createContext({ addItemToCart: () => {} }) }
})
vi.mock('../contexts/cart.context', () => ({ default: MockCartContext }))

import React from 'react'
import Products from '../pages/products/products'
import { AuthContext } from '../contexts/auth.context'
import CartContext from '../contexts/cart.context'

/**
 * Minimal component that replicates the exact onError handler from products.jsx
 * for isolated handler-level testing.
 */
function ProductCard({ product }) {
  return (
    <div className="box">
      <img
        src={product.imageUrl}
        className="image"
        alt="product"
        onError={(e) => {
          if (!e.target.dataset.fallback) {
            e.target.dataset.fallback = 'true'
            e.target.src = PLACEHOLDER_IMAGE
          }
        }}
      />
      <div className="price">Rs. {product.price}</div>
      <div className="name">{product.productName}</div>
    </div>
  )
}

function renderProductCards(products) {
  return render(
    <div>
      {products.map((p) => (
        <ProductCard key={p.id} product={p} />
      ))}
    </div>
  )
}

describe('Products — image fallback handler (US-007 / PURELY-22)', () => {
  const products = [
    { id: '1', productName: 'Alpha', price: 100, imageUrl: 'http://broken/a.png' },
    { id: '2', productName: 'Beta', price: 200, imageUrl: 'http://good/b.png' },
  ]

  it('renders product images with correct src', () => {
    renderProductCards(products)
    const images = screen.getAllByAltText('product')
    expect(images.length).toBe(2)
    expect(images[0].src).toBe('http://broken/a.png')
    expect(images[1].src).toBe('http://good/b.png')
  })

  it('sets placeholder image on error for broken image', () => {
    renderProductCards(products)
    const images = screen.getAllByAltText('product')
    const brokenImg = images[0]

    fireEvent.error(brokenImg)

    expect(brokenImg.src).toBe(PLACEHOLDER_IMAGE)
    expect(brokenImg.dataset.fallback).toBe('true')
  })

  it('does NOT loop — guard prevents infinite fallback cycle', () => {
    renderProductCards(products)
    const images = screen.getAllByAltText('product')
    const brokenImg = images[0]

    fireEvent.error(brokenImg)
    const srcAfterFirst = brokenImg.src

    // Second error should NOT change src — data-fallback guard prevents it
    fireEvent.error(brokenImg)
    expect(brokenImg.src).toBe(srcAfterFirst)
    expect(brokenImg.dataset.fallback).toBe('true')
  })

  it('good image is not affected by fallback logic until error fires', () => {
    renderProductCards(products)
    const images = screen.getAllByAltText('product')
    const goodImg = images[1]

    // No error fired → original src retained, no data-fallback attribute
    expect(goodImg.src).toBe('http://good/b.png')
    expect(goodImg.dataset.fallback).toBeUndefined()
  })

  it('placeholder constant matches the SVG used in products.jsx', () => {
    // Verify the placeholder is a valid data URI SVG
    expect(PLACEHOLDER_IMAGE).toMatch(/^data:image\/svg\+xml,/)
    expect(PLACEHOLDER_IMAGE).toContain('No Image')
  })
})

// CR-001 fix: Smoke-render test with the REAL Products component
describe('Products — real component smoke test (CR-001)', () => {
  it('renders real Products component with <img> elements that have onError handlers', () => {
    const cartCtx = { addItemToCart: vi.fn(), removeItemFromCart: vi.fn(), cart: { cartItems: [] }, cartError: false, isProcessingCart: false, getCartInformation: vi.fn() }
    const authCtx = { user: null, toggleUser: vi.fn() }

    render(
      <AuthContext.Provider value={authCtx}>
        <CartContext.Provider value={cartCtx}>
          <MemoryRouter initialEntries={['/products/All']}>
            <Routes>
              <Route path="/products/:category" element={<Products />} />
            </Routes>
          </MemoryRouter>
        </CartContext.Provider>
      </AuthContext.Provider>
    )

    const images = screen.getAllByAltText('product')
    expect(images.length).toBeGreaterThanOrEqual(1)

    // Verify onError fallback works on the real component's <img>
    const img = images[0]
    fireEvent.error(img)
    expect(img.src).toBe(PLACEHOLDER_IMAGE)
    expect(img.dataset.fallback).toBe('true')
  })
})
