// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.service;

import com.purely.wishlist.client.CartServiceClient;
import com.purely.wishlist.client.ProductServiceClient;
import com.purely.wishlist.dto.*;
import com.purely.wishlist.exception.DuplicateItemException;
import com.purely.wishlist.exception.ResourceNotFoundException;
import com.purely.wishlist.exception.ServiceUnavailableException;
import com.purely.wishlist.model.ShareToken;
import com.purely.wishlist.model.WishlistItem;
import com.purely.wishlist.repository.ShareTokenRepository;
import com.purely.wishlist.repository.WishlistRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link WishlistService} with Mockito mocks.
 *
 * <p>Tests business logic in isolation with mocked repositories and
 * OpenFeign clients. Covers success, error, and edge-case scenarios
 * per acceptance criteria in US-001 through US-005.</p>
 */
@ExtendWith(MockitoExtension.class)
class WishlistServiceTest {

    @Mock
    private WishlistRepository wishlistRepository;

    @Mock
    private ShareTokenRepository shareTokenRepository;

    @Mock
    private ProductServiceClient productServiceClient;

    @Mock
    private CartServiceClient cartServiceClient;

    @InjectMocks
    private WishlistService wishlistService;

    private static final String USER_ID = "user-123";
    private static final String PRODUCT_ID = "prod-456";

    private ProductDto sampleProduct;
    private WishlistItem sampleItem;

    @BeforeEach
    void setUp() {
        sampleProduct = ProductDto.builder()
                .id(PRODUCT_ID)
                .productName("Test Product")
                .price(29.99)
                .description("A test product")
                .imageUrl("https://example.com/img.jpg")
                .categoryId("cat-1")
                .categoryName("Electronics")
                .build();

        sampleItem = WishlistItem.builder()
                .id("item-1")
                .userId(USER_ID)
                .productId(PRODUCT_ID)
                .addedAt(LocalDateTime.now())
                .build();
    }

    // ========================= US-001: Add to Wishlist =========================

    @Test
    @DisplayName("US-001: addToWishlist - success saves item and returns 201")
    void addToWishlist_success() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(false);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(sampleProduct).build()));
        when(wishlistRepository.save(any(WishlistItem.class))).thenReturn(sampleItem);

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.addToWishlist(USER_ID, PRODUCT_ID);

        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertTrue(response.getBody().isSuccess());
        verify(wishlistRepository).save(any(WishlistItem.class));
    }

    @Test
    @DisplayName("US-001: addToWishlist - duplicate throws DuplicateItemException")
    void addToWishlist_duplicate_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(true);

        DuplicateItemException exception = assertThrows(DuplicateItemException.class,
                () -> wishlistService.addToWishlist(USER_ID, PRODUCT_ID));

        assertEquals("Product already in wishlist", exception.getMessage());
        verify(wishlistRepository, never()).save(any());
    }

    @Test
    @DisplayName("US-001: addToWishlist - product not found throws ResourceNotFoundException")
    void addToWishlist_productNotFound_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(false);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(null).build()));

        assertThrows(ResourceNotFoundException.class,
                () -> wishlistService.addToWishlist(USER_ID, PRODUCT_ID));

        verify(wishlistRepository, never()).save(any());
    }

    @Test
    @DisplayName("US-001: addToWishlist - product-service unavailable throws ServiceUnavailableException")
    void addToWishlist_serviceUnavailable_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(false);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenThrow(new RuntimeException("Connection refused"));

        assertThrows(ServiceUnavailableException.class,
                () -> wishlistService.addToWishlist(USER_ID, PRODUCT_ID));

        verify(wishlistRepository, never()).save(any());
    }

    // ========================= US-002: Remove from Wishlist =========================

    @Test
    @DisplayName("US-002: removeFromWishlist - success returns 204")
    void removeFromWishlist_success() {
        doNothing().when(wishlistRepository).deleteByUserIdAndProductId(USER_ID, PRODUCT_ID);

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.removeFromWishlist(USER_ID, PRODUCT_ID);

        assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
        verify(wishlistRepository).deleteByUserIdAndProductId(USER_ID, PRODUCT_ID);
    }

    @Test
    @DisplayName("US-002: removeFromWishlist - idempotent for non-existent item")
    void removeFromWishlist_nonExistent_stillReturns204() {
        doNothing().when(wishlistRepository).deleteByUserIdAndProductId(USER_ID, "non-existent");

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.removeFromWishlist(USER_ID, "non-existent");

        assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
    }

    // ========================= US-003: List Wishlist Items =========================

    @Test
    @DisplayName("US-003: getWishlistItems - returns enriched items")
    void getWishlistItems_success_returnsEnrichedItems() {
        when(wishlistRepository.findByUserId(USER_ID)).thenReturn(List.of(sampleItem));
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(sampleProduct).build()));

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.getWishlistItems(USER_ID);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertTrue(response.getBody().isSuccess());

        @SuppressWarnings("unchecked")
        List<WishlistItemResponse> items = (List<WishlistItemResponse>) response.getBody().getResponse();
        assertEquals(1, items.size());
        assertEquals("Test Product", items.get(0).getProductName());
        assertTrue(items.get(0).isAvailable());
    }

    @Test
    @DisplayName("US-003: getWishlistItems - empty wishlist returns empty list")
    void getWishlistItems_empty_returnsEmptyList() {
        when(wishlistRepository.findByUserId(USER_ID)).thenReturn(Collections.emptyList());

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.getWishlistItems(USER_ID);

        assertEquals(HttpStatus.OK, response.getStatusCode());

        @SuppressWarnings("unchecked")
        List<WishlistItemResponse> items = (List<WishlistItemResponse>) response.getBody().getResponse();
        assertTrue(items.isEmpty());
    }

    // ========================= US-004: Move to Cart =========================

    @Test
    @DisplayName("US-004: moveToCart - success adds to cart and removes from wishlist")
    void moveToCart_success() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(true);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(sampleProduct).build()));
        when(cartServiceClient.addItemToCart(eq(USER_ID), any(CartItemRequestDto.class)))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.builder().isSuccess(true).build()));
        doNothing().when(wishlistRepository).deleteByUserIdAndProductId(USER_ID, PRODUCT_ID);

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.moveToCart(USER_ID, PRODUCT_ID);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertTrue(response.getBody().isSuccess());
        verify(cartServiceClient).addItemToCart(eq(USER_ID), any(CartItemRequestDto.class));
        verify(wishlistRepository).deleteByUserIdAndProductId(USER_ID, PRODUCT_ID);
    }

    @Test
    @DisplayName("US-004: moveToCart - item not in wishlist throws ResourceNotFoundException")
    void moveToCart_notInWishlist_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(false);

        assertThrows(ResourceNotFoundException.class,
                () -> wishlistService.moveToCart(USER_ID, PRODUCT_ID));

        verify(cartServiceClient, never()).addItemToCart(anyString(), any());
    }

    @Test
    @DisplayName("US-004: moveToCart - cart-service unavailable throws ServiceUnavailableException")
    void moveToCart_cartUnavailable_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(true);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(sampleProduct).build()));
        when(cartServiceClient.addItemToCart(eq(USER_ID), any(CartItemRequestDto.class)))
                .thenThrow(new RuntimeException("Connection refused"));

        assertThrows(ServiceUnavailableException.class,
                () -> wishlistService.moveToCart(USER_ID, PRODUCT_ID));

        // Verify item was NOT removed from wishlist
        verify(wishlistRepository, never()).deleteByUserIdAndProductId(anyString(), anyString());
    }

    @Test
    @DisplayName("US-004: moveToCart - product no longer available throws ResourceNotFoundException")
    void moveToCart_productUnavailable_throwsException() {
        when(wishlistRepository.existsByUserIdAndProductId(USER_ID, PRODUCT_ID)).thenReturn(true);
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(null).build()));

        assertThrows(ResourceNotFoundException.class,
                () -> wishlistService.moveToCart(USER_ID, PRODUCT_ID));

        verify(cartServiceClient, never()).addItemToCart(anyString(), any());
    }

    // ========================= US-005: Share Wishlist =========================

    @Test
    @DisplayName("US-005: shareWishlist - generates new token when none exists")
    void shareWishlist_generatesNewToken() {
        when(shareTokenRepository.findByUserId(USER_ID)).thenReturn(Optional.empty());
        when(shareTokenRepository.save(any(ShareToken.class))).thenAnswer(invocation -> {
            ShareToken token = invocation.getArgument(0);
            token.setId("token-id-1");
            return token;
        });

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.shareWishlist(USER_ID);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertTrue(response.getBody().isSuccess());
        verify(shareTokenRepository).save(any(ShareToken.class));
    }

    @Test
    @DisplayName("US-005: shareWishlist - returns existing token if one exists")
    void shareWishlist_returnsExistingToken() {
        ShareToken existingToken = ShareToken.builder()
                .id("token-id-1")
                .userId(USER_ID)
                .token("existing-uuid-token")
                .createdAt(LocalDateTime.now())
                .build();
        when(shareTokenRepository.findByUserId(USER_ID)).thenReturn(Optional.of(existingToken));

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.shareWishlist(USER_ID);

        assertEquals(HttpStatus.OK, response.getStatusCode());
        verify(shareTokenRepository, never()).save(any());

        @SuppressWarnings("unchecked")
        ShareResponse shareResponse = (ShareResponse) response.getBody().getResponse();
        assertEquals("existing-uuid-token", shareResponse.getShareToken());
    }

    @Test
    @DisplayName("US-005: getSharedWishlist - valid token returns items")
    void getSharedWishlist_validToken_returnsItems() {
        ShareToken token = ShareToken.builder()
                .userId(USER_ID)
                .token("valid-token")
                .createdAt(LocalDateTime.now())
                .build();
        when(shareTokenRepository.findByToken("valid-token")).thenReturn(Optional.of(token));
        when(wishlistRepository.findByUserId(USER_ID)).thenReturn(List.of(sampleItem));
        when(productServiceClient.getProductById(PRODUCT_ID))
                .thenReturn(ResponseEntity.ok(ApiResponseDto.<ProductDto>builder()
                        .isSuccess(true).response(sampleProduct).build()));

        ResponseEntity<ApiResponseDto<?>> response = wishlistService.getSharedWishlist("valid-token");

        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertTrue(response.getBody().isSuccess());
    }

    @Test
    @DisplayName("US-005: getSharedWishlist - invalid token throws ResourceNotFoundException")
    void getSharedWishlist_invalidToken_throwsException() {
        when(shareTokenRepository.findByToken("invalid-token")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class,
                () -> wishlistService.getSharedWishlist("invalid-token"));
    }

}
