apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.wishlist.label }} 
spec:
  selector:
    app: {{ .Values.wishlist.label }}
  ports:
    - port: {{ .Values.wishlist.service.port }}
      targetPort: {{ .Values.wishlist.containerPort }}
      protocol: TCP
  type: {{ .Values.wishlist.service.type }}
