apiVersion: v2
name: wishlist-service
description: A Helm chart for Kubernetes — Wishlist/Favorites microservice for the Purely e-commerce platform
type: application
version: 0.1.0
appVersion: "1.0.0"
