// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.service;

import com.purely.wishlist.client.CartServiceClient;
import com.purely.wishlist.client.ProductServiceClient;
import com.purely.wishlist.dto.*;
import com.purely.wishlist.exception.DuplicateItemException;
import com.purely.wishlist.exception.ResourceNotFoundException;
import com.purely.wishlist.exception.ServiceUnavailableException;
import com.purely.wishlist.model.ShareToken;
import com.purely.wishlist.model.WishlistItem;
import com.purely.wishlist.repository.ShareTokenRepository;
import com.purely.wishlist.repository.WishlistRepository;
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Core business logic for the wishlist-service.
 *
 * <p>Handles add/remove/list/share/move-to-cart operations on wishlist items.
 * Follows the service pattern established by {@code CartServiceImpl} in the
 * existing Purely codebase — uses {@code @Component}, Lombok {@code @Slf4j},
 * and returns {@code ResponseEntity<ApiResponseDto<?>>} for all operations.</p>
 *
 * <p>Resilience4j {@code @CircuitBreaker} annotations protect calls to
 * product-service and cart-service from cascading failures.</p>
 */
@Component
@Slf4j
public class WishlistService {

    @Autowired
    private WishlistRepository wishlistRepository;

    @Autowired
    private ShareTokenRepository shareTokenRepository;

    @Autowired
    private ProductServiceClient productServiceClient;

    @Autowired
    private CartServiceClient cartServiceClient;

    /**
     * Add a product to the user's wishlist.
     *
     * <p>Validates product existence via product-service before saving.
     * Duplicate additions are rejected with HTTP 409.</p>
     *
     * @param userId    the authenticated user's identifier
     * @param productId the product to add
     * @return 201 CREATED on success
     * @throws DuplicateItemException       if the product is already in the wishlist
     * @throws ResourceNotFoundException    if the product does not exist
     * @throws ServiceUnavailableException  if product-service is unreachable
     */
    @CircuitBreaker(name = "productService", fallbackMethod = "addToWishlistFallback")
    public ResponseEntity<ApiResponseDto<?>> addToWishlist(String userId, String productId) {
        // Check for duplicate before calling product-service
        if (wishlistRepository.existsByUserIdAndProductId(userId, productId)) {
            throw new DuplicateItemException("Product already in wishlist");
        }

        // Validate product existence via product-service
        try {
            ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                    productServiceClient.getProductById(productId);
            if (productResponse.getBody() == null
                    || !productResponse.getBody().isSuccess()
                    || productResponse.getBody().getResponse() == null) {
                throw new ResourceNotFoundException("Product not found with id " + productId);
            }
        } catch (ResourceNotFoundException e) {
            throw e;
        } catch (DuplicateItemException e) {
            throw e;
        } catch (Exception e) {
            log.error("Failed to validate product via product-service: {}", e.getMessage());
            throw new ServiceUnavailableException("Product service is currently unavailable. Please try again later.");
        }

        // Save the wishlist item
        WishlistItem item = WishlistItem.builder()
                .userId(userId)
                .productId(productId)
                .addedAt(LocalDateTime.now())
                .build();
        wishlistRepository.save(item);

        log.info("Product {} added to wishlist for user {}", productId, userId);

        return ResponseEntity.status(HttpStatus.CREATED).body(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Product added to wishlist successfully!")
                        .build()
        );
    }

    /**
     * Fallback method when product-service circuit breaker is open.
     *
     * @param userId    the user identifier
     * @param productId the product identifier
     * @param throwable the cause of the fallback
     * @return 503 SERVICE_UNAVAILABLE response
     */
    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> addToWishlistFallback(String userId, String productId, Throwable throwable) {
        log.warn("Circuit breaker open for productService during add. userId={}, productId={}, reason={}",
                userId, productId, throwable.getMessage());
        if (throwable instanceof DuplicateItemException) {
            throw (DuplicateItemException) throwable;
        }
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        throw new ServiceUnavailableException("Product service is currently unavailable. Please try again later.");
    }

    /**
     * Remove a product from the user's wishlist.
     *
     * <p>Idempotent: returns 204 even if the item was not in the wishlist.</p>
     *
     * @param userId    the authenticated user's identifier
     * @param productId the product to remove
     * @return 204 NO_CONTENT
     */
    public ResponseEntity<ApiResponseDto<?>> removeFromWishlist(String userId, String productId) {
        wishlistRepository.deleteByUserIdAndProductId(userId, productId);
        log.info("Product {} removed from wishlist for user {}", productId, userId);

        return ResponseEntity.status(HttpStatus.NO_CONTENT).body(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Product removed from wishlist")
                        .build()
        );
    }

    /**
     * List all wishlist items for a user, enriched with product details.
     *
     * <p>Product details (name, price, image, availability) are fetched from
     * product-service. If product-service is unavailable, items are returned
     * with {@code available = false} and placeholder values.</p>
     *
     * @param userId the authenticated user's identifier
     * @return 200 OK with list of enriched wishlist items
     */
    @CircuitBreaker(name = "productService", fallbackMethod = "getWishlistItemsFallback")
    public ResponseEntity<ApiResponseDto<?>> getWishlistItems(String userId) {
        List<WishlistItem> items = wishlistRepository.findByUserId(userId);
        List<WishlistItemResponse> enrichedItems = enrichWithProductDetails(items);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist retrieved successfully")
                        .response(enrichedItems)
                        .build()
        );
    }

    /**
     * Fallback when product-service is unavailable during wishlist listing.
     * Returns items with stale/unavailable flags instead of failing completely.
     *
     * @param userId    the user identifier
     * @param throwable the cause of the fallback
     * @return 200 OK with items flagged as unavailable
     */
    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> getWishlistItemsFallback(String userId, Throwable throwable) {
        log.warn("Circuit breaker open for productService during list. userId={}, reason={}",
                userId, throwable.getMessage());
        List<WishlistItem> items = wishlistRepository.findByUserId(userId);
        List<WishlistItemResponse> staleItems = items.stream()
                .map(item -> WishlistItemResponse.builder()
                        .productId(item.getProductId())
                        .productName("Unavailable")
                        .imageUrl("")
                        .price(0.0)
                        .available(false)
                        .addedAt(item.getAddedAt())
                        .build())
                .toList();

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist retrieved with limited product data (product service unavailable)")
                        .response(staleItems)
                        .build()
        );
    }

    /**
     * Move a wishlist item to the user's shopping cart.
     *
     * <p>This is a two-step operation: (1) call cart-service to add the item,
     * then (2) remove the item from the wishlist. If cart-service fails,
     * the item remains in the wishlist and HTTP 503 is returned.</p>
     *
     * @param userId    the authenticated user's identifier
     * @param productId the product to move
     * @return 200 OK on success
     * @throws ResourceNotFoundException    if the product is not in the wishlist
     * @throws ServiceUnavailableException  if cart-service is unreachable
     */
    @CircuitBreaker(name = "cartService", fallbackMethod = "moveToCartFallback")
    public ResponseEntity<ApiResponseDto<?>> moveToCart(String userId, String productId) {
        // Verify item exists in wishlist
        if (!wishlistRepository.existsByUserIdAndProductId(userId, productId)) {
            throw new ResourceNotFoundException("Product not found in wishlist");
        }

        // Validate product is still available via product-service
        try {
            ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                    productServiceClient.getProductById(productId);
            if (productResponse.getBody() == null
                    || !productResponse.getBody().isSuccess()
                    || productResponse.getBody().getResponse() == null) {
                throw new ResourceNotFoundException("Product no longer available");
            }
        } catch (ResourceNotFoundException e) {
            throw e;
        } catch (Exception e) {
            log.error("Failed to validate product before move-to-cart: {}", e.getMessage());
            throw new ServiceUnavailableException("Unable to verify product availability. Please try again later.");
        }

        // Add to cart via cart-service
        try {
            CartItemRequestDto cartRequest = CartItemRequestDto.builder()
                    .productId(productId)
                    .quantity(1)
                    .build();
            cartServiceClient.addItemToCart(userId, cartRequest);
        } catch (Exception e) {
            log.error("Failed to add item to cart via cart-service: {}", e.getMessage());
            throw new ServiceUnavailableException("Cart service is currently unavailable. Item stays in your wishlist.");
        }

        // Remove from wishlist after successful cart addition
        wishlistRepository.deleteByUserIdAndProductId(userId, productId);
        log.info("Product {} moved from wishlist to cart for user {}", productId, userId);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Item moved to cart successfully!")
                        .build()
        );
    }

    /**
     * Fallback when cart-service circuit breaker is open during move-to-cart.
     *
     * @param userId    the user identifier
     * @param productId the product identifier
     * @param throwable the cause of the fallback
     * @return 503 SERVICE_UNAVAILABLE, item stays in wishlist
     */
    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> moveToCartFallback(String userId, String productId, Throwable throwable) {
        log.warn("Circuit breaker open for cartService during moveToCart. userId={}, productId={}, reason={}",
                userId, productId, throwable.getMessage());
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        throw new ServiceUnavailableException("Cart service is currently unavailable. Item stays in your wishlist.");
    }

    /**
     * Generate or retrieve a shareable link for the user's wishlist.
     *
     * <p>If a share token already exists for this user, the existing token
     * is returned. Otherwise, a new UUID-based token is generated.</p>
     *
     * @param userId the authenticated user's identifier
     * @return 200 OK with the share token and URL
     */
    public ResponseEntity<ApiResponseDto<?>> shareWishlist(String userId) {
        // Check if a share token already exists for this user
        ShareToken shareToken = shareTokenRepository.findByUserId(userId)
                .orElseGet(() -> {
                    ShareToken newToken = ShareToken.builder()
                            .userId(userId)
                            .token(UUID.randomUUID().toString())
                            .createdAt(LocalDateTime.now())
                            .build();
                    return shareTokenRepository.save(newToken);
                });

        ShareResponse shareResponse = ShareResponse.builder()
                .shareToken(shareToken.getToken())
                .shareUrl("/api/wishlist/shared/" + shareToken.getToken())
                .build();

        log.info("Wishlist share token generated for user {}: {}", userId, shareToken.getToken());

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist share link generated")
                        .response(shareResponse)
                        .build()
        );
    }

    /**
     * Retrieve a shared wishlist by token (public, no authentication required).
     *
     * <p>Product details are enriched from product-service. If product-service
     * is unavailable, items are returned with stale/unavailable flags.</p>
     *
     * @param shareToken the UUID share token from the shareable URL
     * @return 200 OK with the read-only wishlist
     * @throws ResourceNotFoundException if the share token is invalid
     */
    @CircuitBreaker(name = "productService", fallbackMethod = "getSharedWishlistFallback")
    public ResponseEntity<ApiResponseDto<?>> getSharedWishlist(String shareToken) {
        ShareToken tokenDoc = shareTokenRepository.findByToken(shareToken)
                .orElseThrow(() -> new ResourceNotFoundException("Wishlist not found"));

        List<WishlistItem> items = wishlistRepository.findByUserId(tokenDoc.getUserId());
        List<WishlistItemResponse> enrichedItems = enrichWithProductDetails(items);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Shared wishlist retrieved successfully")
                        .response(enrichedItems)
                        .build()
        );
    }

    /**
     * Fallback for shared wishlist when product-service is unavailable.
     *
     * @param shareToken the share token
     * @param throwable  the cause
     * @return 200 OK with items flagged as unavailable
     */
    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> getSharedWishlistFallback(String shareToken, Throwable throwable) {
        log.warn("Circuit breaker open for productService during shared wishlist. token={}, reason={}",
                shareToken, throwable.getMessage());
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        ShareToken tokenDoc = shareTokenRepository.findByToken(shareToken)
                .orElseThrow(() -> new ResourceNotFoundException("Wishlist not found"));
        List<WishlistItem> items = wishlistRepository.findByUserId(tokenDoc.getUserId());
        List<WishlistItemResponse> staleItems = items.stream()
                .map(item -> WishlistItemResponse.builder()
                        .productId(item.getProductId())
                        .productName("Unavailable")
                        .imageUrl("")
                        .price(0.0)
                        .available(false)
                        .addedAt(item.getAddedAt())
                        .build())
                .toList();

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Shared wishlist retrieved with limited product data")
                        .response(staleItems)
                        .build()
        );
    }

    /**
     * Enrich wishlist items with product details from product-service.
     *
     * <p>For each item, a synchronous call is made to product-service.
     * If a single product lookup fails, that item is flagged as unavailable
     * rather than failing the entire list.</p>
     *
     * @param items the raw wishlist items from MongoDB
     * @return enriched response DTOs with product details
     */
    private List<WishlistItemResponse> enrichWithProductDetails(List<WishlistItem> items) {
        List<WishlistItemResponse> enrichedItems = new ArrayList<>();

        for (WishlistItem item : items) {
            try {
                ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                        productServiceClient.getProductById(item.getProductId());

                if (productResponse.getBody() != null
                        && productResponse.getBody().isSuccess()
                        && productResponse.getBody().getResponse() != null) {
                    ProductDto product = productResponse.getBody().getResponse();
                    enrichedItems.add(WishlistItemResponse.builder()
                            .productId(item.getProductId())
                            .productName(product.getProductName())
                            .imageUrl(product.getImageUrl())
                            .price(product.getPrice())
                            .available(true)
                            .addedAt(item.getAddedAt())
                            .build());
                } else {
                    // Product not found — mark as unavailable
                    enrichedItems.add(buildUnavailableItem(item));
                }
            } catch (Exception e) {
                log.warn("Failed to fetch product details for productId={}: {}",
                        item.getProductId(), e.getMessage());
                enrichedItems.add(buildUnavailableItem(item));
            }
        }

        return enrichedItems;
    }

    /**
     * Build a WishlistItemResponse with unavailable/stale data flags.
     *
     * @param item the raw wishlist item
     * @return a response DTO marked as unavailable
     */
    private WishlistItemResponse buildUnavailableItem(WishlistItem item) {
        return WishlistItemResponse.builder()
                .productId(item.getProductId())
                .productName("Unavailable")
                .imageUrl("")
                .price(0.0)
                .available(false)
                .addedAt(item.getAddedAt())
                .build();
    }

}
