// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.service;

import com.purely.wishlist.client.CartServiceClient;
import com.purely.wishlist.client.ProductServiceClient;
import com.purely.wishlist.dto.*;
import com.purely.wishlist.exception.DuplicateItemException;
import com.purely.wishlist.exception.ResourceNotFoundException;
import com.purely.wishlist.exception.ServiceUnavailableException;
import com.purely.wishlist.model.ShareToken;
import com.purely.wishlist.model.WishlistItem;
import com.purely.wishlist.repository.ShareTokenRepository;
import com.purely.wishlist.repository.WishlistRepository;
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Component
@Slf4j
public class WishlistService {

    @Autowired
    private WishlistRepository wishlistRepository;

    @Autowired
    private ShareTokenRepository shareTokenRepository;

    @Autowired
    private ProductServiceClient productServiceClient;

    @Autowired
    private CartServiceClient cartServiceClient;

    @CircuitBreaker(name = "productService", fallbackMethod = "addToWishlistFallback")
    public ResponseEntity<ApiResponseDto<?>> addToWishlist(String userId, String productId) {
        if (wishlistRepository.existsByUserIdAndProductId(userId, productId)) {
            throw new DuplicateItemException("Product already in wishlist");
        }

        try {
            ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                    productServiceClient.getProductById(productId);
            if (productResponse.getBody() == null
                    || !productResponse.getBody().isSuccess()
                    || productResponse.getBody().getResponse() == null) {
                throw new ResourceNotFoundException("Product not found with id " + productId);
            }
        } catch (ResourceNotFoundException e) {
            throw e;
        } catch (DuplicateItemException e) {
            throw e;
        } catch (Exception e) {
            log.error("Failed to validate product via product-service: {}", e.getMessage());
            throw new ServiceUnavailableException("Product service is currently unavailable. Please try again later.");
        }

        WishlistItem item = WishlistItem.builder()
                .userId(userId)
                .productId(productId)
                .addedAt(LocalDateTime.now())
                .build();
        wishlistRepository.save(item);

        log.info("Product {} added to wishlist for user {}", productId, userId);

        return ResponseEntity.status(HttpStatus.CREATED).body(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Product added to wishlist successfully!")
                        .build()
        );
    }

    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> addToWishlistFallback(String userId, String productId, Throwable throwable) {
        log.warn("Circuit breaker open for productService during add. userId={}, productId={}, reason={}",
                userId, productId, throwable.getMessage());
        if (throwable instanceof DuplicateItemException) {
            throw (DuplicateItemException) throwable;
        }
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        throw new ServiceUnavailableException("Product service is currently unavailable. Please try again later.");
    }

    public ResponseEntity<ApiResponseDto<?>> removeFromWishlist(String userId, String productId) {
        wishlistRepository.deleteByUserIdAndProductId(userId, productId);
        log.info("Product {} removed from wishlist for user {}", productId, userId);

        return ResponseEntity.status(HttpStatus.NO_CONTENT).body(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Product removed from wishlist")
                        .build()
        );
    }

    @CircuitBreaker(name = "productService", fallbackMethod = "getWishlistItemsFallback")
    public ResponseEntity<ApiResponseDto<?>> getWishlistItems(String userId) {
        List<WishlistItem> items = wishlistRepository.findByUserId(userId);
        List<WishlistItemResponse> enrichedItems = enrichWithProductDetails(items);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist retrieved successfully")
                        .response(enrichedItems)
                        .build()
        );
    }

    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> getWishlistItemsFallback(String userId, Throwable throwable) {
        log.warn("Circuit breaker open for productService during list. userId={}, reason={}",
                userId, throwable.getMessage());
        List<WishlistItem> items = wishlistRepository.findByUserId(userId);
        List<WishlistItemResponse> staleItems = items.stream()
                .map(item -> WishlistItemResponse.builder()
                        .productId(item.getProductId())
                        .productName("Unavailable")
                        .imageUrl("")
                        .price(0.0)
                        .available(false)
                        .addedAt(item.getAddedAt())
                        .build())
                .toList();

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist retrieved with limited product data (product service unavailable)")
                        .response(staleItems)
                        .build()
        );
    }

    @CircuitBreaker(name = "cartService", fallbackMethod = "moveToCartFallback")
    public ResponseEntity<ApiResponseDto<?>> moveToCart(String userId, String productId) {
        if (!wishlistRepository.existsByUserIdAndProductId(userId, productId)) {
            throw new ResourceNotFoundException("Product not found in wishlist");
        }

        try {
            ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                    productServiceClient.getProductById(productId);
            if (productResponse.getBody() == null
                    || !productResponse.getBody().isSuccess()
                    || productResponse.getBody().getResponse() == null) {
                throw new ResourceNotFoundException("Product no longer available");
            }
        } catch (ResourceNotFoundException e) {
            throw e;
        } catch (Exception e) {
            log.error("Failed to validate product before move-to-cart: {}", e.getMessage());
            throw new ServiceUnavailableException("Unable to verify product availability. Please try again later.");
        }

        try {
            CartItemRequestDto cartRequest = CartItemRequestDto.builder()
                    .productId(productId)
                    .quantity(1)
                    .build();
            cartServiceClient.addItemToCart(userId, cartRequest);
        } catch (Exception e) {
            log.error("Failed to add item to cart via cart-service: {}", e.getMessage());
            throw new ServiceUnavailableException("Cart service is currently unavailable. Item stays in your wishlist.");
        }

        wishlistRepository.deleteByUserIdAndProductId(userId, productId);
        log.info("Product {} moved from wishlist to cart for user {}", productId, userId);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Item moved to cart successfully!")
                        .build()
        );
    }

    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> moveToCartFallback(String userId, String productId, Throwable throwable) {
        log.warn("Circuit breaker open for cartService during moveToCart. userId={}, productId={}, reason={}",
                userId, productId, throwable.getMessage());
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        throw new ServiceUnavailableException("Cart service is currently unavailable. Item stays in your wishlist.");
    }

    public ResponseEntity<ApiResponseDto<?>> shareWishlist(String userId) {
        ShareToken shareToken = shareTokenRepository.findByUserId(userId)
                .orElseGet(() -> {
                    ShareToken newToken = ShareToken.builder()
                            .userId(userId)
                            .token(UUID.randomUUID().toString())
                            .createdAt(LocalDateTime.now())
                            .build();
                    return shareTokenRepository.save(newToken);
                });

        ShareResponse shareResponse = ShareResponse.builder()
                .shareToken(shareToken.getToken())
                .shareUrl("/api/wishlist/shared/" + shareToken.getToken())
                .build();

        log.info("Wishlist share token generated for user {}: {}", userId, shareToken.getToken());

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Wishlist share link generated")
                        .response(shareResponse)
                        .build()
        );
    }

    @CircuitBreaker(name = "productService", fallbackMethod = "getSharedWishlistFallback")
    public ResponseEntity<ApiResponseDto<?>> getSharedWishlist(String shareToken) {
        ShareToken tokenDoc = shareTokenRepository.findByToken(shareToken)
                .orElseThrow(() -> new ResourceNotFoundException("Wishlist not found"));

        List<WishlistItem> items = wishlistRepository.findByUserId(tokenDoc.getUserId());
        List<WishlistItemResponse> enrichedItems = enrichWithProductDetails(items);

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Shared wishlist retrieved successfully")
                        .response(enrichedItems)
                        .build()
        );
    }

    @SuppressWarnings("unused")
    private ResponseEntity<ApiResponseDto<?>> getSharedWishlistFallback(String shareToken, Throwable throwable) {
        log.warn("Circuit breaker open for productService during shared wishlist. token={}, reason={}",
                shareToken, throwable.getMessage());
        if (throwable instanceof ResourceNotFoundException) {
            throw (ResourceNotFoundException) throwable;
        }
        ShareToken tokenDoc = shareTokenRepository.findByToken(shareToken)
                .orElseThrow(() -> new ResourceNotFoundException("Wishlist not found"));
        List<WishlistItem> items = wishlistRepository.findByUserId(tokenDoc.getUserId());
        List<WishlistItemResponse> staleItems = items.stream()
                .map(item -> WishlistItemResponse.builder()
                        .productId(item.getProductId())
                        .productName("Unavailable")
                        .imageUrl("")
                        .price(0.0)
                        .available(false)
                        .addedAt(item.getAddedAt())
                        .build())
                .toList();

        return ResponseEntity.ok(
                ApiResponseDto.builder()
                        .isSuccess(true)
                        .message("Shared wishlist retrieved with limited product data")
                        .response(staleItems)
                        .build()
        );
    }

    private List<WishlistItemResponse> enrichWithProductDetails(List<WishlistItem> items) {
        List<WishlistItemResponse> enrichedItems = new ArrayList<>();

        for (WishlistItem item : items) {
            try {
                ResponseEntity<ApiResponseDto<ProductDto>> productResponse =
                        productServiceClient.getProductById(item.getProductId());

                if (productResponse.getBody() != null
                        && productResponse.getBody().isSuccess()
                        && productResponse.getBody().getResponse() != null) {
                    ProductDto product = productResponse.getBody().getResponse();
                    enrichedItems.add(WishlistItemResponse.builder()
                            .productId(item.getProductId())
                            .productName(product.getProductName())
                            .imageUrl(product.getImageUrl())
                            .price(product.getPrice())
                            .available(true)
                            .addedAt(item.getAddedAt())
                            .build());
                } else {
                    enrichedItems.add(buildUnavailableItem(item));
                }
            } catch (Exception e) {
                log.warn("Failed to fetch product details for productId={}: {}",
                        item.getProductId(), e.getMessage());
                enrichedItems.add(buildUnavailableItem(item));
            }
        }

        return enrichedItems;
    }

    private WishlistItemResponse buildUnavailableItem(WishlistItem item) {
        return WishlistItemResponse.builder()
                .productId(item.getProductId())
                .productName("Unavailable")
                .imageUrl("")
                .price(0.0)
                .available(false)
                .addedAt(item.getAddedAt())
                .build();
    }

}
