// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development
// Shared image constants (extracted per CR-002 to eliminate duplication)

/** Inline SVG placeholder for broken product images (BUG-3 / ADR-003). Network-free fallback. */
export const PLACEHOLDER_IMAGE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 200 200'%3E%3Crect fill='%23f0f0f0' width='200' height='200'/%3E%3Ctext fill='%23999' font-family='Arial' font-size='14' text-anchor='middle' x='100' y='105'%3ENo Image%3C/text%3E%3C/svg%3E";
