// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.exception;

/**
 * Thrown when a user attempts to add a product that already exists in their wishlist.
 * Maps to HTTP 409 via {@link GlobalExceptionHandler}.
 */
public class DuplicateItemException extends RuntimeException {

    public DuplicateItemException(String message) {
        super(message);
    }

}
