// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
// ---------------------------------------------------------------------------
// Wishlist Service — MongoDB Index Initialization Script
//
// Belt-and-suspenders index creation that runs independently of Spring Data
// annotations. Use this script:
//   - As a Docker entrypoint init script (mounted into /docker-entrypoint-initdb.d/)
//   - As a manual migration step during first deployment
//   - In CI pipelines for database provisioning
//
// Spring Data @CompoundIndex / @Indexed annotations on the Java models also
// create these indexes at application startup. This script ensures indexes
// exist even if the application has not yet started (e.g., during data
// migration or manual seeding).
//
// Collections:
//   wishlist_items  — one document per user-product pair
//   share_tokens    — one document per shareable wishlist link
//
// Usage:
//   mongosh purely_wishlist_service < init-indexes.js
// ---------------------------------------------------------------------------

db = db.getSiblingDB('purely_wishlist_service');

// ── wishlist_items collection ─────────────────────────────────────────────

// Compound unique index: prevents duplicate wishlist entries for the same
// user + product combination. Supports the primary query pattern:
//   "find all wishlist items for userId X"
// and the duplicate-check pattern:
//   "does userId X already have productId Y in their wishlist?"
db.wishlist_items.createIndex(
  { userId: 1, productId: 1 },
  {
    name: 'idx_user_product_unique',
    unique: true,
    background: true
  }
);
print('Created index: idx_user_product_unique on wishlist_items (userId, productId)');

// Single-field index on userId: optimises "get all items for user" and
// "count items for user" queries when the compound index cannot be used
// (e.g., sorting by addedAt).
db.wishlist_items.createIndex(
  { userId: 1 },
  {
    name: 'idx_userId',
    background: true
  }
);
print('Created index: idx_userId on wishlist_items (userId)');

// Single-field index on addedAt: supports "recently added" queries and
// TTL-style cleanup if a retention policy is introduced later.
db.wishlist_items.createIndex(
  { addedAt: -1 },
  {
    name: 'idx_addedAt_desc',
    background: true
  }
);
print('Created index: idx_addedAt_desc on wishlist_items (addedAt DESC)');

// ── share_tokens collection ───────────────────────────────────────────────

// Unique index on token: ensures no two share links collide and supports
// the primary lookup pattern: "find share token by UUID token value".
db.share_tokens.createIndex(
  { token: 1 },
  {
    name: 'idx_token_unique',
    unique: true,
    background: true
  }
);
print('Created index: idx_token_unique on share_tokens (token)');

// Single-field index on userId: supports "find all share tokens for user"
// and "does this user already have a share token?" queries.
db.share_tokens.createIndex(
  { userId: 1 },
  {
    name: 'idx_sharetoken_userId',
    background: true
  }
);
print('Created index: idx_sharetoken_userId on share_tokens (userId)');

// ── Verify ────────────────────────────────────────────────────────────────
print('\n--- Index verification ---');
print('wishlist_items indexes:');
printjson(db.wishlist_items.getIndexes());
print('share_tokens indexes:');
printjson(db.share_tokens.getIndexes());
print('--- Wishlist service index initialization complete ---');
