// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
db = db.getSiblingDB('purely_wishlist_service');

db.wishlist_items.createIndex(
  { userId: 1, productId: 1 },
  { name: 'idx_user_product_unique', unique: true, background: true }
);
print('Created index: idx_user_product_unique on wishlist_items (userId, productId)');

db.wishlist_items.createIndex(
  { userId: 1 },
  { name: 'idx_userId', background: true }
);
print('Created index: idx_userId on wishlist_items (userId)');

db.wishlist_items.createIndex(
  { addedAt: -1 },
  { name: 'idx_addedAt_desc', background: true }
);
print('Created index: idx_addedAt_desc on wishlist_items (addedAt DESC)');

db.share_tokens.createIndex(
  { token: 1 },
  { name: 'idx_token_unique', unique: true, background: true }
);
print('Created index: idx_token_unique on share_tokens (token)');

db.share_tokens.createIndex(
  { userId: 1 },
  { name: 'idx_sharetoken_userId', background: true }
);
print('Created index: idx_sharetoken_userId on share_tokens (userId)');

print('\n--- Index verification ---');
print('wishlist_items indexes:');
printjson(db.wishlist_items.getIndexes());
print('share_tokens indexes:');
printjson(db.share_tokens.getIndexes());
print('--- Wishlist service index initialization complete ---');
