// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.purely.wishlist.dto.AddToWishlistRequest;
import com.purely.wishlist.dto.ApiResponseDto;
import com.purely.wishlist.dto.ShareResponse;
import com.purely.wishlist.dto.WishlistItemResponse;
import com.purely.wishlist.exception.DuplicateItemException;
import com.purely.wishlist.exception.GlobalExceptionHandler;
import com.purely.wishlist.exception.ResourceNotFoundException;
import com.purely.wishlist.exception.ServiceUnavailableException;
import com.purely.wishlist.security.AuthTokenFilter;
import com.purely.wishlist.security.WebSecurityConfig;
import com.purely.wishlist.service.WishlistService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.bean.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * MockMvc integration tests for {@link WishlistController}.
 *
 * <p>Tests all REST endpoints with mocked service layer. Validates
 * HTTP status codes, response structure, and error handling per
 * the acceptance criteria in US-001 through US-005.</p>
 */
@WebMvcTest(WishlistController.class)
class WishlistControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private WishlistService wishlistService;

    @Autowired
    private ObjectMapper objectMapper;

    private static final String USER_ID = "user-123";
    private static final String PRODUCT_ID = "prod-456";

    // ========================= US-001: Add to Wishlist =========================

    @Test
    @DisplayName("US-001: POST /wishlist/add - success returns 201")
    void addToWishlist_success_returns201() throws Exception {
        when(wishlistService.addToWishlist(eq(USER_ID), eq(PRODUCT_ID)))
                .thenReturn(ResponseEntity.status(HttpStatus.CREATED).body(
                        ApiResponseDto.builder().isSuccess(true).message("Product added to wishlist successfully!").build()));

        AddToWishlistRequest request = AddToWishlistRequest.builder().productId(PRODUCT_ID).build();

        mockMvc.perform(post("/wishlist/add")
                        .with(user(USER_ID).roles("USER"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.message").value("Product added to wishlist successfully!"));
    }

    @Test
    @DisplayName("US-001: POST /wishlist/add - duplicate returns 409")
    void addToWishlist_duplicate_returns409() throws Exception {
        when(wishlistService.addToWishlist(eq(USER_ID), eq(PRODUCT_ID)))
                .thenThrow(new DuplicateItemException("Product already in wishlist"));

        AddToWishlistRequest request = AddToWishlistRequest.builder().productId(PRODUCT_ID).build();

        mockMvc.perform(post("/wishlist/add")
                        .with(user(USER_ID).roles("USER"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.isSuccess").value(false))
                .andExpect(jsonPath("$.message").value("Product already in wishlist"));
    }

    @Test
    @DisplayName("US-001: POST /wishlist/add - product not found returns 404")
    void addToWishlist_productNotFound_returns404() throws Exception {
        when(wishlistService.addToWishlist(eq(USER_ID), eq(PRODUCT_ID)))
                .thenThrow(new ResourceNotFoundException("Product not found with id " + PRODUCT_ID));

        AddToWishlistRequest request = AddToWishlistRequest.builder().productId(PRODUCT_ID).build();

        mockMvc.perform(post("/wishlist/add")
                        .with(user(USER_ID).roles("USER"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.isSuccess").value(false));
    }

    @Test
    @DisplayName("US-001: POST /wishlist/add - blank productId returns 400")
    void addToWishlist_blankProductId_returns400() throws Exception {
        AddToWishlistRequest request = AddToWishlistRequest.builder().productId("").build();

        mockMvc.perform(post("/wishlist/add")
                        .with(user(USER_ID).roles("USER"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest());
    }

    // ========================= US-002: Remove from Wishlist =========================

    @Test
    @DisplayName("US-002: DELETE /wishlist/remove/{productId} - success returns 204")
    void removeFromWishlist_success_returns204() throws Exception {
        when(wishlistService.removeFromWishlist(eq(USER_ID), eq(PRODUCT_ID)))
                .thenReturn(ResponseEntity.status(HttpStatus.NO_CONTENT).body(
                        ApiResponseDto.builder().isSuccess(true).message("Product removed from wishlist").build()));

        mockMvc.perform(delete("/wishlist/remove/{productId}", PRODUCT_ID)
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isNoContent());
    }

    @Test
    @DisplayName("US-002: DELETE /wishlist/remove/{productId} - idempotent for non-existent item")
    void removeFromWishlist_nonExistent_returns204() throws Exception {
        when(wishlistService.removeFromWishlist(eq(USER_ID), eq("non-existent")))
                .thenReturn(ResponseEntity.status(HttpStatus.NO_CONTENT).body(
                        ApiResponseDto.builder().isSuccess(true).message("Product removed from wishlist").build()));

        mockMvc.perform(delete("/wishlist/remove/{productId}", "non-existent")
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isNoContent());
    }

    // ========================= US-003: List Wishlist Items =========================

    @Test
    @DisplayName("US-003: GET /wishlist/get/byUser - returns list of items")
    void getWishlistItems_success_returnsList() throws Exception {
        List<WishlistItemResponse> items = List.of(
                WishlistItemResponse.builder()
                        .productId(PRODUCT_ID)
                        .productName("Test Product")
                        .imageUrl("https://example.com/img.jpg")
                        .price(29.99)
                        .available(true)
                        .addedAt(LocalDateTime.now())
                        .build()
        );

        when(wishlistService.getWishlistItems(eq(USER_ID)))
                .thenReturn(ResponseEntity.ok(
                        ApiResponseDto.builder().isSuccess(true).response(items).build()));

        mockMvc.perform(get("/wishlist/get/byUser")
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.response[0].productId").value(PRODUCT_ID))
                .andExpect(jsonPath("$.response[0].productName").value("Test Product"))
                .andExpect(jsonPath("$.response[0].available").value(true));
    }

    @Test
    @DisplayName("US-003: GET /wishlist/get/byUser - empty wishlist returns empty array")
    void getWishlistItems_empty_returnsEmptyArray() throws Exception {
        when(wishlistService.getWishlistItems(eq(USER_ID)))
                .thenReturn(ResponseEntity.ok(
                        ApiResponseDto.builder().isSuccess(true).response(Collections.emptyList()).build()));

        mockMvc.perform(get("/wishlist/get/byUser")
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.response").isEmpty());
    }

    // ========================= US-004: Move to Cart =========================

    @Test
    @DisplayName("US-004: POST /wishlist/moveToCart/{productId} - success returns 200")
    void moveToCart_success_returns200() throws Exception {
        when(wishlistService.moveToCart(eq(USER_ID), eq(PRODUCT_ID)))
                .thenReturn(ResponseEntity.ok(
                        ApiResponseDto.builder().isSuccess(true).message("Item moved to cart successfully!").build()));

        mockMvc.perform(post("/wishlist/moveToCart/{productId}", PRODUCT_ID)
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.message").value("Item moved to cart successfully!"));
    }

    @Test
    @DisplayName("US-004: POST /wishlist/moveToCart/{productId} - cart-service unavailable returns 503")
    void moveToCart_cartUnavailable_returns503() throws Exception {
        when(wishlistService.moveToCart(eq(USER_ID), eq(PRODUCT_ID)))
                .thenThrow(new ServiceUnavailableException("Cart service is currently unavailable. Item stays in your wishlist."));

        mockMvc.perform(post("/wishlist/moveToCart/{productId}", PRODUCT_ID)
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isServiceUnavailable())
                .andExpect(jsonPath("$.isSuccess").value(false));
    }

    @Test
    @DisplayName("US-004: POST /wishlist/moveToCart/{productId} - product not in wishlist returns 404")
    void moveToCart_notInWishlist_returns404() throws Exception {
        when(wishlistService.moveToCart(eq(USER_ID), eq(PRODUCT_ID)))
                .thenThrow(new ResourceNotFoundException("Product not found in wishlist"));

        mockMvc.perform(post("/wishlist/moveToCart/{productId}", PRODUCT_ID)
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.isSuccess").value(false));
    }

    // ========================= US-005: Share Wishlist =========================

    @Test
    @DisplayName("US-005: POST /wishlist/share - success returns share token")
    void shareWishlist_success_returnsShareToken() throws Exception {
        ShareResponse shareResponse = ShareResponse.builder()
                .shareToken("abc-uuid-token")
                .shareUrl("/api/wishlist/shared/abc-uuid-token")
                .build();

        when(wishlistService.shareWishlist(eq(USER_ID)))
                .thenReturn(ResponseEntity.ok(
                        ApiResponseDto.builder().isSuccess(true).response(shareResponse).build()));

        mockMvc.perform(post("/wishlist/share")
                        .with(user(USER_ID).roles("USER")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.response.shareToken").value("abc-uuid-token"))
                .andExpect(jsonPath("$.response.shareUrl").value("/api/wishlist/shared/abc-uuid-token"));
    }

    @Test
    @DisplayName("US-005: GET /wishlist/shared/{shareToken} - valid token returns items (no auth)")
    void getSharedWishlist_validToken_returnsItems() throws Exception {
        List<WishlistItemResponse> items = List.of(
                WishlistItemResponse.builder()
                        .productId(PRODUCT_ID)
                        .productName("Shared Product")
                        .imageUrl("https://example.com/shared.jpg")
                        .price(49.99)
                        .available(true)
                        .addedAt(LocalDateTime.now())
                        .build()
        );

        when(wishlistService.getSharedWishlist(eq("valid-token")))
                .thenReturn(ResponseEntity.ok(
                        ApiResponseDto.builder().isSuccess(true).response(items).build()));

        mockMvc.perform(get("/wishlist/shared/{shareToken}", "valid-token"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.isSuccess").value(true))
                .andExpect(jsonPath("$.response[0].productName").value("Shared Product"));
    }

    @Test
    @DisplayName("US-005: GET /wishlist/shared/{shareToken} - invalid token returns 404")
    void getSharedWishlist_invalidToken_returns404() throws Exception {
        when(wishlistService.getSharedWishlist(eq("invalid-token")))
                .thenThrow(new ResourceNotFoundException("Wishlist not found"));

        mockMvc.perform(get("/wishlist/shared/{shareToken}", "invalid-token"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.isSuccess").value(false))
                .andExpect(jsonPath("$.message").value("Wishlist not found"));
    }

}
