// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.config;

import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.Duration;

/**
 * Resilience4j circuit breaker configuration for the wishlist-service.
 *
 * <p><strong>New to project</strong>: This is the first service in the Purely platform
 * to adopt Resilience4j circuit breakers. The configuration protects OpenFeign
 * calls to product-service and cart-service from cascading failures.</p>
 *
 * <h3>Circuit Breaker Behavior</h3>
 * <ul>
 *   <li>Opens after 50% failure rate in a sliding window of 10 calls</li>
 *   <li>Waits 10 seconds in open state before allowing half-open probes</li>
 *   <li>Allows 3 probe calls in half-open state</li>
 * </ul>
 *
 * <p>YAML-based configuration in {@code application.yml} defines per-instance
 * settings. This class provides a programmatic fallback registry.</p>
 */
@Configuration
public class Resilience4jConfig {

    /**
     * Creates a custom CircuitBreakerRegistry with sensible defaults
     * for inter-service communication.
     *
     * @return a configured CircuitBreakerRegistry bean
     */
    @Bean
    public CircuitBreakerRegistry circuitBreakerRegistry() {
        CircuitBreakerConfig defaultConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(50)
                .waitDurationInOpenState(Duration.ofSeconds(10))
                .permittedNumberOfCallsInHalfOpenState(3)
                .slidingWindowSize(10)
                .slidingWindowType(CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)
                .minimumNumberOfCalls(5)
                .build();

        return CircuitBreakerRegistry.of(defaultConfig);
    }

}
