// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useState, useEffect } from "react";
import API_BASE_URL from "./apiConfig";
import axios from "axios";

function WishlistService() {
  const [wishlistItems, setWishlistItems] = useState([]);
  const [wishlistError, setError] = useState(false);
  const [isProcessingWishlist, setProcessing] = useState(false);
  const user = JSON.parse(localStorage.getItem("user"));

  const authHeader = () => {
    return { Authorization: `${user?.type}${user?.token}` };
  };

  const addToWishlist = async (productId) => {
    setProcessing(true);
    let success = false;
    await axios
      .post(
        `${API_BASE_URL}/wishlist/add`,
        { productId },
        { headers: authHeader() }
      )
      .then(() => {
        setError(false);
        success = true;
      })
      .catch(() => {
        setError(true);
      });
    setProcessing(false);
    getWishlistItems();
    return success;
  };

  const removeFromWishlist = async (productId) => {
    setProcessing(true);
    await axios
      .delete(`${API_BASE_URL}/wishlist/remove/${productId}`, {
        headers: authHeader(),
      })
      .then(() => {
        setError(false);
      })
      .catch(() => {
        setError(true);
      });
    setProcessing(false);
    getWishlistItems();
  };

  const getWishlistItems = async () => {
    if (!user?.token) {
      setWishlistItems([]);
      setError(false);
      return;
    }
    setProcessing(true);
    await axios
      .get(`${API_BASE_URL}/wishlist/get/byUser`, {
        headers: authHeader(),
      })
      .then((response) => {
        setError(false);
        setWishlistItems(response.data.response || []);
      })
      .catch(() => {
        setWishlistItems([]);
        setError(true);
      });
    setProcessing(false);
  };

  const moveToCart = async (productId) => {
    setProcessing(true);
    let success = false;
    await axios
      .post(
        `${API_BASE_URL}/wishlist/moveToCart/${productId}`,
        {},
        { headers: authHeader() }
      )
      .then(() => {
        setError(false);
        success = true;
      })
      .catch(() => {
        setError(true);
      });
    setProcessing(false);
    getWishlistItems();
    return success;
  };

  const shareWishlist = async () => {
    setProcessing(true);
    let result = null;
    await axios
      .post(
        `${API_BASE_URL}/wishlist/share`,
        {},
        { headers: authHeader() }
      )
      .then((response) => {
        setError(false);
        result = response.data.response;
      })
      .catch(() => {
        setError(true);
      });
    setProcessing(false);
    return result;
  };

  const getSharedWishlist = async (shareToken) => {
    setProcessing(true);
    let items = [];
    await axios
      .get(`${API_BASE_URL}/wishlist/shared/${shareToken}`)
      .then((response) => {
        setError(false);
        items = response.data.response || [];
      })
      .catch(() => {
        setError(true);
      });
    setProcessing(false);
    return items;
  };

  const isInWishlist = (productId) => {
    return wishlistItems.some((item) => item.productId === productId);
  };

  useEffect(() => {
    getWishlistItems();
  }, []);

  return {
    wishlistItems,
    wishlistError,
    isProcessingWishlist,
    addToWishlist,
    removeFromWishlist,
    getWishlistItems,
    moveToCart,
    shareWishlist,
    getSharedWishlist,
    isInWishlist,
  };
}

export default WishlistService;
