// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import axios from "axios";
import SharedWishlistPage from "../../frontend/src/pages/wishlist/SharedWishlistPage";

vi.mock("axios");

const sharedItems = [
  {
    productId: "p1",
    productName: "Shared Product A",
    imageUrl: "https://example.com/a.jpg",
    price: 29.99,
    available: true,
  },
  {
    productId: "p2",
    productName: "Shared Product B",
    imageUrl: "https://example.com/b.jpg",
    price: 59.99,
    available: false,
  },
];

const renderSharedPage = (token = "valid-token-123") => {
  return render(
    <MemoryRouter initialEntries={[`/wishlist/shared/${token}`]}>
      <Routes>
        <Route
          path="/wishlist/shared/:shareToken"
          element={<SharedWishlistPage />}
        />
      </Routes>
    </MemoryRouter>
  );
};

describe("SharedWishlistPage", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ─── US-005: Shared wishlist public view ───

  it("renders shared items on successful fetch", async () => {
    axios.get.mockResolvedValueOnce({ data: sharedItems });
    renderSharedPage();

    await waitFor(() => {
      expect(screen.getByText("Shared Product A")).toBeInTheDocument();
      expect(screen.getByText("Shared Product B")).toBeInTheDocument();
    });
  });

  it("renders page title", async () => {
    axios.get.mockResolvedValueOnce({ data: sharedItems });
    renderSharedPage();

    expect(screen.getByText("Shared Wishlist")).toBeInTheDocument();
  });

  it("displays product prices correctly", async () => {
    axios.get.mockResolvedValueOnce({ data: sharedItems });
    renderSharedPage();

    await waitFor(() => {
      expect(screen.getByText("Rs. 29.99")).toBeInTheDocument();
      expect(screen.getByText("Rs. 59.99")).toBeInTheDocument();
    });
  });

  it("displays availability badges", async () => {
    axios.get.mockResolvedValueOnce({ data: sharedItems });
    renderSharedPage();

    await waitFor(() => {
      expect(screen.getByText("In Stock")).toBeInTheDocument();
      expect(screen.getByText("Out of Stock")).toBeInTheDocument();
    });
  });

  // ─── Error handling ───

  it("shows error message for invalid/expired token", async () => {
    axios.get.mockRejectedValueOnce(new Error("404 Not Found"));
    renderSharedPage("invalid-token");

    await waitFor(() => {
      expect(
        screen.getByText(/unable to load this shared wishlist/i)
      ).toBeInTheDocument();
    });
  });

  // ─── Empty state ───

  it("shows empty state when shared wishlist has no items", async () => {
    axios.get.mockResolvedValueOnce({ data: [] });
    renderSharedPage();

    await waitFor(() => {
      expect(
        screen.getByText("This shared wishlist is empty.")
      ).toBeInTheDocument();
    });
  });

  it("renders Browse Products link in empty state", async () => {
    axios.get.mockResolvedValueOnce({ data: [] });
    renderSharedPage();

    await waitFor(() => {
      expect(screen.getByText("Browse Products")).toBeInTheDocument();
    });
  });

  // ─── API call verification ───

  it("calls correct API endpoint with share token", async () => {
    axios.get.mockResolvedValueOnce({ data: sharedItems });
    renderSharedPage("my-share-token");

    await waitFor(() => {
      expect(axios.get).toHaveBeenCalledWith(
        expect.stringContaining("/wishlist/shared/my-share-token")
      );
    });
  });
});
