// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import WishlistCard from "../../frontend/src/components/wishlist/WishlistCard";
import WishlistContext from "../../frontend/src/contexts/wishlist.context";
import CartContext from "../../frontend/src/contexts/cart.context";

// Sample wishlist item
const sampleItem = {
  productId: "prod-1",
  productName: "Wireless Headphones",
  imageUrl: "https://example.com/headphones.jpg",
  price: 79.99,
  available: true,
  addedAt: "2026-04-01T10:00:00Z",
};

const unavailableItem = { ...sampleItem, available: false };

const defaultWishlistCtx = {
  removeFromWishlist: vi.fn(),
  moveToCart: vi.fn(),
};

const defaultCartCtx = {
  addItemToCart: vi.fn(),
};

const renderCard = (item = sampleItem, wishlistCtx = {}, cartCtx = {}, readOnly = false) => {
  return render(
    <CartContext.Provider value={{ ...defaultCartCtx, ...cartCtx }}>
      <WishlistContext.Provider value={{ ...defaultWishlistCtx, ...wishlistCtx }}>
        <WishlistCard item={item} readOnly={readOnly} />
      </WishlistContext.Provider>
    </CartContext.Provider>
  );
};

describe("WishlistCard", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ─── US-008: Wishlist card rendering ───

  it("renders product name, price, and In Stock badge", () => {
    renderCard();
    expect(screen.getByText("Wireless Headphones")).toBeInTheDocument();
    expect(screen.getByText("Rs. 79.99")).toBeInTheDocument();
    expect(screen.getByText("In Stock")).toBeInTheDocument();
  });

  it("renders Out of Stock badge when item is unavailable", () => {
    renderCard(unavailableItem);
    expect(screen.getByText("Out of Stock")).toBeInTheDocument();
  });

  it("renders product image with correct src and alt", () => {
    renderCard();
    const img = screen.getByAltText("Wireless Headphones");
    expect(img).toHaveAttribute("src", "https://example.com/headphones.jpg");
  });

  it("formats price to two decimal places", () => {
    const intPriceItem = { ...sampleItem, price: 50 };
    renderCard(intPriceItem);
    expect(screen.getByText("Rs. 50.00")).toBeInTheDocument();
  });

  it("handles null price gracefully", () => {
    const nullPriceItem = { ...sampleItem, price: null };
    renderCard(nullPriceItem);
    expect(screen.getByText("Rs. 0.00")).toBeInTheDocument();
  });

  // ─── US-002: Remove button ───

  it("calls removeFromWishlist when Remove button is clicked", async () => {
    const removeFromWishlist = vi.fn();
    renderCard(sampleItem, { removeFromWishlist });

    fireEvent.click(screen.getByTitle("Remove from wishlist"));
    await waitFor(() => expect(removeFromWishlist).toHaveBeenCalledWith("prod-1"));
  });

  // ─── US-004: Move to cart ───

  it("calls moveToCart when Move to Cart button is clicked", async () => {
    const moveToCart = vi.fn();
    renderCard(sampleItem, { moveToCart });

    fireEvent.click(screen.getByTitle("Move to cart"));
    await waitFor(() => expect(moveToCart).toHaveBeenCalledWith("prod-1"));
  });

  it("disables Move to Cart button when item is out of stock", () => {
    renderCard(unavailableItem);
    const cartBtn = screen.getByTitle("Currently unavailable");
    expect(cartBtn).toBeDisabled();
  });

  it("falls back to addItemToCart + removeFromWishlist when moveToCart is null", async () => {
    const addItemToCart = vi.fn();
    const removeFromWishlist = vi.fn();
    renderCard(
      sampleItem,
      { removeFromWishlist, moveToCart: null },
      { addItemToCart }
    );

    fireEvent.click(screen.getByText("Move to Cart"));
    await waitFor(() => {
      expect(addItemToCart).toHaveBeenCalledWith("prod-1", 1);
      expect(removeFromWishlist).toHaveBeenCalledWith("prod-1");
    });
  });

  // ─── Read-only mode (shared wishlist) ───

  it("hides action buttons in readOnly mode", () => {
    renderCard(sampleItem, {}, {}, true);
    expect(screen.queryByText("Move to Cart")).not.toBeInTheDocument();
    expect(screen.queryByText("Remove")).not.toBeInTheDocument();
  });

  it("still renders product info in readOnly mode", () => {
    renderCard(sampleItem, {}, {}, true);
    expect(screen.getByText("Wireless Headphones")).toBeInTheDocument();
    expect(screen.getByText("Rs. 79.99")).toBeInTheDocument();
  });
});
