// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect } from "vitest";
import { useContext } from "react";
import { render, screen } from "@testing-library/react";
import WishlistContext from "../../frontend/src/contexts/wishlist.context";

/**
 * Tests for the WishlistContext module.
 *
 * WishlistContext is a bare createContext() — the provider value is assembled
 * in App.jsx via WishlistService(). These tests validate the context contract
 * and default behaviour.
 */

function TestConsumer() {
  const ctx = useContext(WishlistContext);
  return <div data-testid="ctx-value">{ctx === undefined ? "undefined" : "defined"}</div>;
}

function TestConsumerWithValue() {
  const ctx = useContext(WishlistContext);
  return (
    <div>
      <span data-testid="items-count">{ctx.wishlistItems?.length ?? 0}</span>
      <span data-testid="has-add">{typeof ctx.addToWishlist === "function" ? "yes" : "no"}</span>
      <span data-testid="has-remove">{typeof ctx.removeFromWishlist === "function" ? "yes" : "no"}</span>
      <span data-testid="has-isIn">{typeof ctx.isInWishlist === "function" ? "yes" : "no"}</span>
    </div>
  );
}

describe("WishlistContext", () => {
  it("default context value is undefined (no provider)", () => {
    render(<TestConsumer />);
    expect(screen.getByTestId("ctx-value").textContent).toBe("undefined");
  });

  it("provides wishlistItems when wrapped in provider", () => {
    const value = {
      wishlistItems: [{ productId: "p1" }, { productId: "p2" }],
      addToWishlist: () => {},
      removeFromWishlist: () => {},
      isInWishlist: () => false,
    };
    render(
      <WishlistContext.Provider value={value}>
        <TestConsumerWithValue />
      </WishlistContext.Provider>
    );
    expect(screen.getByTestId("items-count").textContent).toBe("2");
  });

  it("provides action functions via provider", () => {
    const value = {
      wishlistItems: [],
      addToWishlist: () => {},
      removeFromWishlist: () => {},
      isInWishlist: () => false,
    };
    render(
      <WishlistContext.Provider value={value}>
        <TestConsumerWithValue />
      </WishlistContext.Provider>
    );
    expect(screen.getByTestId("has-add").textContent).toBe("yes");
    expect(screen.getByTestId("has-remove").textContent).toBe("yes");
    expect(screen.getByTestId("has-isIn").textContent).toBe("yes");
  });

  it("allows empty wishlistItems array", () => {
    const value = {
      wishlistItems: [],
      addToWishlist: () => {},
      removeFromWishlist: () => {},
      isInWishlist: () => false,
    };
    render(
      <WishlistContext.Provider value={value}>
        <TestConsumerWithValue />
      </WishlistContext.Provider>
    );
    expect(screen.getByTestId("items-count").textContent).toBe("0");
  });
});
