// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import WishlistButton from "../../frontend/src/components/wishlist/WishlistButton";
import WishlistContext from "../../frontend/src/contexts/wishlist.context";
import { AuthContext } from "../../frontend/src/contexts/auth.context";

// Mock react-router-dom navigate
const mockNavigate = vi.fn();
vi.mock("react-router-dom", async () => {
  const actual = await vi.importActual("react-router-dom");
  return { ...actual, useNavigate: () => mockNavigate };
});

// Helpers
const defaultWishlistCtx = {
  addToWishlist: vi.fn(),
  removeFromWishlist: vi.fn(),
  isInWishlist: vi.fn(() => false),
};

const renderButton = (wishlistCtx = {}, authUser = { id: "u1" }, props = {}) => {
  const ctx = { ...defaultWishlistCtx, ...wishlistCtx };
  return render(
    <AuthContext.Provider value={{ user: authUser }}>
      <WishlistContext.Provider value={ctx}>
        <MemoryRouter>
          <WishlistButton productId="prod-1" {...props} />
        </MemoryRouter>
      </WishlistContext.Provider>
    </AuthContext.Provider>
  );
};

describe("WishlistButton", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ─── US-007: Heart toggle on product cards ───

  it("renders outline heart when product is NOT in wishlist", () => {
    renderButton({ isInWishlist: () => false });
    const btn = screen.getByRole("button", { name: /add to wishlist/i });
    expect(btn).toBeInTheDocument();
    expect(btn).not.toHaveClass("wishlisted");
  });

  it("renders filled heart when product IS in wishlist", () => {
    renderButton({ isInWishlist: () => true });
    const btn = screen.getByRole("button", { name: /remove from wishlist/i });
    expect(btn).toBeInTheDocument();
    expect(btn).toHaveClass("wishlisted");
  });

  it("calls addToWishlist when clicking un-wishlisted product", async () => {
    const addToWishlist = vi.fn();
    renderButton({ isInWishlist: () => false, addToWishlist });

    fireEvent.click(screen.getByRole("button"));
    await waitFor(() => expect(addToWishlist).toHaveBeenCalledWith("prod-1"));
  });

  it("calls removeFromWishlist when clicking wishlisted product", async () => {
    const removeFromWishlist = vi.fn();
    renderButton({ isInWishlist: () => true, removeFromWishlist });

    fireEvent.click(screen.getByRole("button"));
    await waitFor(() => expect(removeFromWishlist).toHaveBeenCalledWith("prod-1"));
  });

  it("redirects unauthenticated user to /auth/login", () => {
    renderButton({}, null);
    fireEvent.click(screen.getByRole("button"));
    expect(mockNavigate).toHaveBeenCalledWith("/auth/login");
  });

  it("does NOT call add/remove for unauthenticated user", () => {
    const addToWishlist = vi.fn();
    const removeFromWishlist = vi.fn();
    renderButton({ addToWishlist, removeFromWishlist }, null);

    fireEvent.click(screen.getByRole("button"));
    expect(addToWishlist).not.toHaveBeenCalled();
    expect(removeFromWishlist).not.toHaveBeenCalled();
  });

  it("applies custom className prop", () => {
    renderButton({}, { id: "u1" }, { className: "extra-cls" });
    expect(screen.getByRole("button")).toHaveClass("extra-cls");
  });

  it("adds pop animation class briefly on toggle", async () => {
    renderButton({ isInWishlist: () => false, addToWishlist: vi.fn() });
    const btn = screen.getByRole("button");

    fireEvent.click(btn);
    expect(btn).toHaveClass("wishlist-btn--pop");
  });
});
