// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { renderHook, act, waitFor } from "@testing-library/react";
import axios from "axios";
import WishlistService from "../../frontend/src/api-service/wishlist.service";

vi.mock("axios");

const mockUser = { token: "jwt-token-123", type: "Bearer " };

describe("WishlistService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Seed localStorage with a logged-in user
    Storage.prototype.getItem = vi.fn((key) => {
      if (key === "user") return JSON.stringify(mockUser);
      return null;
    });
    // Mock the initial getWishlistItems call on mount
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // ─── US-001: addToWishlist ───

  it("addToWishlist sends POST and returns true on success", async () => {
    axios.post.mockResolvedValueOnce({ data: { isSuccess: true } });
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    let success;
    await act(async () => {
      success = await result.current.addToWishlist("prod-1");
    });

    expect(success).toBe(true);
    expect(axios.post).toHaveBeenCalledWith(
      expect.stringContaining("/wishlist/add"),
      { productId: "prod-1" },
      { headers: { Authorization: "Bearer jwt-token-123" } }
    );
  });

  it("addToWishlist sets error on failure", async () => {
    axios.post.mockRejectedValueOnce(new Error("409 Conflict"));
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    await act(async () => {
      await result.current.addToWishlist("prod-1");
    });

    expect(result.current.wishlistError).toBe(true);
  });

  // ─── US-002: removeFromWishlist ───

  it("removeFromWishlist sends DELETE request", async () => {
    axios.delete.mockResolvedValueOnce({});
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    await act(async () => {
      await result.current.removeFromWishlist("prod-1");
    });

    expect(axios.delete).toHaveBeenCalledWith(
      expect.stringContaining("/wishlist/remove/prod-1"),
      { headers: { Authorization: "Bearer jwt-token-123" } }
    );
  });

  it("removeFromWishlist sets error on failure", async () => {
    axios.delete.mockRejectedValueOnce(new Error("500"));
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    await act(async () => {
      await result.current.removeFromWishlist("prod-1");
    });

    expect(result.current.wishlistError).toBe(true);
  });

  // ─── US-003: getWishlistItems ───

  it("getWishlistItems fetches and sets items", async () => {
    const items = [{ productId: "p1" }, { productId: "p2" }];
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: items } });

    const { result } = renderHook(() => WishlistService());

    await waitFor(() => {
      expect(result.current.wishlistItems).toEqual(items);
    });
  });

  it("getWishlistItems resets to empty when no token", async () => {
    Storage.prototype.getItem = vi.fn(() => null);

    const { result } = renderHook(() => WishlistService());

    await waitFor(() => {
      expect(result.current.wishlistItems).toEqual([]);
      expect(result.current.wishlistError).toBe(false);
    });
  });

  it("getWishlistItems sets error on network failure", async () => {
    axios.get.mockRejectedValue(new Error("Network Error"));

    const { result } = renderHook(() => WishlistService());

    await waitFor(() => {
      expect(result.current.wishlistError).toBe(true);
      expect(result.current.wishlistItems).toEqual([]);
    });
  });

  // ─── US-004: moveToCart ───

  it("moveToCart sends POST to correct endpoint", async () => {
    axios.post.mockResolvedValueOnce({ data: { isSuccess: true } });
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    let success;
    await act(async () => {
      success = await result.current.moveToCart("prod-1");
    });

    expect(success).toBe(true);
    expect(axios.post).toHaveBeenCalledWith(
      expect.stringContaining("/wishlist/moveToCart/prod-1"),
      {},
      { headers: { Authorization: "Bearer jwt-token-123" } }
    );
  });

  it("moveToCart sets error on failure", async () => {
    axios.post.mockRejectedValueOnce(new Error("503 Service Unavailable"));
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    await act(async () => {
      await result.current.moveToCart("prod-1");
    });

    expect(result.current.wishlistError).toBe(true);
  });

  // ─── US-005: shareWishlist ───

  it("shareWishlist returns share data on success", async () => {
    const shareData = { shareToken: "abc", shareUrl: "/shared/abc" };
    axios.post.mockResolvedValueOnce({ data: { isSuccess: true, message: "OK", response: shareData } });
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    let shareResult;
    await act(async () => {
      shareResult = await result.current.shareWishlist();
    });

    expect(shareResult).toEqual(shareData);
  });

  it("shareWishlist returns null on error", async () => {
    axios.post.mockRejectedValueOnce(new Error("500"));
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: [] } });

    const { result } = renderHook(() => WishlistService());

    let shareResult;
    await act(async () => {
      shareResult = await result.current.shareWishlist();
    });

    expect(shareResult).toBeNull();
  });

  // ─── US-005: getSharedWishlist ───

  it("getSharedWishlist fetches items by share token", async () => {
    const items = [{ productId: "p1", productName: "Shared" }];
    axios.get
      .mockResolvedValueOnce({ data: { isSuccess: true, message: "OK", response: [] } }) // initial mount fetch
      .mockResolvedValueOnce({ data: { isSuccess: true, message: "OK", response: items } }); // getSharedWishlist

    const { result } = renderHook(() => WishlistService());

    let sharedItems;
    await act(async () => {
      sharedItems = await result.current.getSharedWishlist("token-xyz");
    });

    expect(sharedItems).toEqual(items);
  });

  // ─── isInWishlist ───

  it("isInWishlist returns true when product exists", async () => {
    const items = [{ productId: "p1" }, { productId: "p2" }];
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: items } });

    const { result } = renderHook(() => WishlistService());

    await waitFor(() => {
      expect(result.current.isInWishlist("p1")).toBe(true);
    });
  });

  it("isInWishlist returns false when product does not exist", async () => {
    const items = [{ productId: "p1" }];
    axios.get.mockResolvedValue({ data: { isSuccess: true, message: "OK", response: items } });

    const { result } = renderHook(() => WishlistService());

    await waitFor(() => {
      expect(result.current.isInWishlist("xx-unknown")).toBe(false);
    });
  });
});
