// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import WishlistPage from "../../frontend/src/pages/wishlist/WishlistPage";
import WishlistContext from "../../frontend/src/contexts/wishlist.context";
import { AuthContext } from "../../frontend/src/contexts/auth.context";
import CartContext from "../../frontend/src/contexts/cart.context";

// Mock navigate
const mockNavigate = vi.fn();
vi.mock("react-router-dom", async () => {
  const actual = await vi.importActual("react-router-dom");
  return { ...actual, useNavigate: () => mockNavigate };
});

// Mock clipboard
Object.assign(navigator, {
  clipboard: { writeText: vi.fn(() => Promise.resolve()) },
});

const sampleItems = [
  {
    productId: "p1",
    productName: "Product One",
    imageUrl: "https://example.com/p1.jpg",
    price: 19.99,
    available: true,
    addedAt: "2026-04-01T10:00:00Z",
  },
  {
    productId: "p2",
    productName: "Product Two",
    imageUrl: "https://example.com/p2.jpg",
    price: 49.99,
    available: false,
    addedAt: "2026-04-02T10:00:00Z",
  },
];

const defaultWishlistCtx = {
  wishlistItems: sampleItems,
  wishlistError: false,
  isProcessingWishlist: false,
  shareWishlist: vi.fn(),
  removeFromWishlist: vi.fn(),
  moveToCart: vi.fn(),
  isInWishlist: vi.fn(),
};

const defaultCartCtx = { addItemToCart: vi.fn() };

const renderPage = (wishlistCtx = {}, authUser = { id: "u1" }) => {
  const ctx = { ...defaultWishlistCtx, ...wishlistCtx };
  return render(
    <AuthContext.Provider value={{ user: authUser }}>
      <CartContext.Provider value={defaultCartCtx}>
        <WishlistContext.Provider value={ctx}>
          <MemoryRouter>
            <WishlistPage />
          </MemoryRouter>
        </WishlistContext.Provider>
      </CartContext.Provider>
    </AuthContext.Provider>
  );
};

describe("WishlistPage", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ─── US-008: Wishlist page rendering ───

  it("renders page title with item count", () => {
    renderPage();
    expect(screen.getByText("My Wishlist")).toBeInTheDocument();
    expect(screen.getByText("(2 items)")).toBeInTheDocument();
  });

  it("renders all wishlist cards", () => {
    renderPage();
    expect(screen.getByText("Product One")).toBeInTheDocument();
    expect(screen.getByText("Product Two")).toBeInTheDocument();
  });

  it("shows singular 'item' label for single item", () => {
    renderPage({ wishlistItems: [sampleItems[0]] });
    expect(screen.getByText("(1 item)")).toBeInTheDocument();
  });

  // ─── Empty state ───

  it("shows empty state when wishlist has no items", () => {
    renderPage({ wishlistItems: [] });
    expect(screen.getByText("Your wishlist is empty.")).toBeInTheDocument();
    expect(screen.getByText("Browse Products")).toBeInTheDocument();
  });

  it("navigates to products page when Browse Products is clicked", () => {
    renderPage({ wishlistItems: [] });
    fireEvent.click(screen.getByText("Browse Products"));
    expect(mockNavigate).toHaveBeenCalledWith("/products/All");
  });

  // ─── Loading & error states ───

  it("shows loading indicator when processing", () => {
    renderPage({ isProcessingWishlist: true });
    // Loading component should be rendered (we check it doesn't show grid)
    expect(screen.queryByText("Product One")).not.toBeInTheDocument();
  });

  it("shows error message when wishlistError is true", () => {
    renderPage({ wishlistError: true });
    expect(
      screen.getByText(/unable to load your wishlist/i)
    ).toBeInTheDocument();
  });

  // ─── US-005: Share functionality ───

  it("renders Share Wishlist button when items exist", () => {
    renderPage();
    expect(screen.getByText("Share Wishlist")).toBeInTheDocument();
  });

  it("does not render Share button when wishlist is empty", () => {
    renderPage({ wishlistItems: [] });
    expect(screen.queryByText("Share Wishlist")).not.toBeInTheDocument();
  });

  it("generates share URL on Share button click", async () => {
    const shareWishlist = vi.fn(() =>
      Promise.resolve({ shareUrl: "https://purely.com/wishlist/shared/abc123" })
    );
    renderPage({ shareWishlist });

    fireEvent.click(screen.getByText("Share Wishlist"));
    await waitFor(() => {
      expect(shareWishlist).toHaveBeenCalled();
    });
  });

  // ─── Authentication redirect ───

  it("redirects to login when user is not authenticated", () => {
    renderPage({}, null);
    expect(mockNavigate).toHaveBeenCalledWith("/auth/login");
  });
});
