// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import WishlistBadge from "../../frontend/src/components/wishlist/WishlistBadge";
import WishlistContext from "../../frontend/src/contexts/wishlist.context";

const renderBadge = (items = []) => {
  return render(
    <WishlistContext.Provider value={{ wishlistItems: items }}>
      <MemoryRouter>
        <WishlistBadge />
      </MemoryRouter>
    </WishlistContext.Provider>
  );
};

describe("WishlistBadge", () => {
  // ─── US-006: Wishlist count badge in header ───

  it("displays (0) when wishlist is empty", () => {
    renderBadge([]);
    expect(screen.getByText("(0)")).toBeInTheDocument();
  });

  it("displays correct count for non-empty wishlist", () => {
    const items = [
      { productId: "p1" },
      { productId: "p2" },
      { productId: "p3" },
    ];
    renderBadge(items);
    expect(screen.getByText("(3)")).toBeInTheDocument();
  });

  it("links to /wishlist", () => {
    renderBadge();
    const link = screen.getByRole("link", { name: /view wishlist/i });
    expect(link).toHaveAttribute("href", "/wishlist");
  });

  it("has accessible aria-label", () => {
    renderBadge();
    expect(screen.getByLabelText("View wishlist")).toBeInTheDocument();
  });

  it("handles null wishlistItems gracefully", () => {
    render(
      <WishlistContext.Provider value={{ wishlistItems: null }}>
        <MemoryRouter>
          <WishlistBadge />
        </MemoryRouter>
      </WishlistContext.Provider>
    );
    expect(screen.getByText("(0)")).toBeInTheDocument();
  });
});
