// Generated by SDLC Agent | 2026-04-07 | purely-cart-bugfix-PURELY-1 | development-test-writer
// Covers: US-001 (PURELY-16) — Fix user-service MongoDB URI
package com.dharshi.userservice;

import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Validates that the application.yml MongoDB URI points to the correct database.
 * BUG-1 fix: URI was incorrectly set to purely_user_service; must be purely_auth_service.
 */
class MongoDbUriConfigTest {

    @Test
    void mongoDbUri_shouldPointToAuthServiceDatabase() throws Exception {
        InputStream is = getClass().getClassLoader().getResourceAsStream("application.yml");
        assertNotNull(is, "application.yml must be on the classpath");

        String content = new String(is.readAllBytes(), StandardCharsets.UTF_8);

        assertTrue(
            content.contains("purely_auth_service"),
            "MongoDB URI must reference 'purely_auth_service' database"
        );
        assertFalse(
            content.contains("purely_user_service"),
            "MongoDB URI must NOT reference the old 'purely_user_service' database"
        );
    }

    @Test
    void mongoDbUri_shouldBeValidMongoConnectionString() throws Exception {
        InputStream is = getClass().getClassLoader().getResourceAsStream("application.yml");
        assertNotNull(is);

        String content = new String(is.readAllBytes(), StandardCharsets.UTF_8);

        assertTrue(
            content.contains("mongodb://"),
            "MongoDB URI must start with 'mongodb://'"
        );
    }
}
