// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document representing a wishlist share token.
 *
 * <p>When a user shares their wishlist, a UUID-based token is generated
 * and persisted. Any visitor can use this token to view a read-only
 * copy of the wishlist without authentication.</p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "share_tokens")
public class ShareToken {

    /** MongoDB auto-generated document identifier. */
    @Id
    private String id;

    /** Identifier of the user who created this share link. */
    private String userId;

    /** UUID-based token used in the shareable URL. Indexed for fast lookups. */
    @Indexed(unique = true)
    private String token;

    /** Timestamp when the share token was created. */
    private LocalDateTime createdAt;

}
