// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * MongoDB document representing a single wishlist item.
 *
 * <p>Each document links one user to one product. A compound unique index
 * on {@code userId} + {@code productId} prevents duplicate entries,
 * enforcing the "no duplicate products in wishlist" business rule at
 * the database level.</p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Document(collection = "wishlist_items")
@CompoundIndex(name = "user_product_unique", def = "{'userId': 1, 'productId': 1}", unique = true)
public class WishlistItem {

    /** MongoDB auto-generated document identifier. */
    @Id
    private String id;

    /** Identifier of the user who owns this wishlist entry. */
    private String userId;

    /** Identifier of the product saved to the wishlist. */
    private String productId;

    /** Timestamp when the product was added to the wishlist. */
    private LocalDateTime addedAt;

}
