// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.client;

import com.purely.wishlist.dto.ApiResponseDto;
import com.purely.wishlist.security.UserDetails;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * OpenFeign declarative client for the auth-service.
 *
 * <p>Communicates via Eureka service discovery using the logical name
 * {@code AUTH-SERVICE}. Used by {@link com.purely.wishlist.security.AuthTokenFilter}
 * to validate JWT tokens and extract user identity.</p>
 */
@FeignClient("AUTH-SERVICE")
public interface AuthServiceClient {

    /**
     * Validate a JWT token and retrieve the associated user details.
     *
     * @param token the JWT token (without "Bearer " prefix)
     * @return API response wrapping {@link UserDetails} with userId and authorities
     */
    @GetMapping("/auth/isValidToken")
    ResponseEntity<ApiResponseDto<UserDetails>> validateToken(@RequestParam String token);

}
