// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.client;

import com.purely.wishlist.dto.ApiResponseDto;
import com.purely.wishlist.dto.CartItemRequestDto;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;

@FeignClient("CART-SERVICE")
public interface CartServiceClient {

    @PostMapping("/cart/add")
    ResponseEntity<ApiResponseDto<?>> addItemToCart(
            @RequestHeader("X-User-Id") String userId,
            @RequestBody CartItemRequestDto requestDto);

}
