// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { createContext } from "react";

const WishlistContext = createContext();

export default WishlistContext;
