// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import axios from "axios";
import API_BASE_URL from "../../api-service/apiConfig";
import Header from "../../components/header/header";
import Footer from "../../components/footer/footer";
import Loading from "../../components/loading/loading";
import Info from "../../components/info/info";
import { PLACEHOLDER_IMAGE } from "../../constants/images";
import "./SharedWishlistPage.css";

function SharedWishlistPage() {
  const { shareToken } = useParams();
  const [items, setItems] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    const fetchSharedWishlist = async () => {
      setIsLoading(true);
      await axios
        .get(`${API_BASE_URL}/wishlist/shared/${shareToken}`)
        .then((response) => {
          setItems(response.data || []);
          setError(false);
        })
        .catch(() => {
          setError(true);
        });
      setIsLoading(false);
    };

    if (shareToken) {
      fetchSharedWishlist();
    }
  }, [shareToken]);

  return (
    <>
      <Header />
      <section className="shared-wishlist-page">
        <h2 className="shared-wishlist-page__title">Shared Wishlist</h2>

        {isLoading && <Loading />}
        {error && (
          <Info message="Unable to load this shared wishlist. The link may be invalid or expired." />
        )}

        {!isLoading && !error && items.length === 0 && (
          <div className="shared-wishlist-page__empty">
            <p>This shared wishlist is empty.</p>
            <Link to="/products/All">
              <button>Browse Products</button>
            </Link>
          </div>
        )}

        {!isLoading && !error && items.length > 0 && (
          <div className="shared-wishlist-page__grid">
            {items.map((item) => (
              <div className="shared-wishlist-card" key={item.productId}>
                <img
                  src={item.imageUrl}
                  alt={item.productName}
                  className="shared-wishlist-card__image"
                  onError={(e) => {
                    if (!e.target.dataset.fallback) {
                      e.target.dataset.fallback = "true";
                      e.target.src = PLACEHOLDER_IMAGE;
                    }
                  }}
                />
                <div className="shared-wishlist-card__info">
                  <h4 className="shared-wishlist-card__name">{item.productName}</h4>
                  <span className="shared-wishlist-card__price">
                    Rs. {parseFloat(item.price || 0).toFixed(2)}
                  </span>
                  <span
                    className={`shared-wishlist-card__availability ${item.available ? "in-stock" : "out-of-stock"}`}
                  >
                    {item.available ? "In Stock" : "Out of Stock"}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
      <Footer />
    </>
  );
}

export default SharedWishlistPage;
