// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
import { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AiOutlineShareAlt } from "react-icons/ai";
import Header from "../../components/header/header";
import Footer from "../../components/footer/footer";
import Loading from "../../components/loading/loading";
import Info from "../../components/info/info";
import WishlistCard from "../../components/wishlist/WishlistCard";
import WishlistContext from "../../contexts/wishlist.context";
import { AuthContext } from "../../contexts/auth.context";
import "./WishlistPage.css";

function WishlistPage() {
  const {
    wishlistItems,
    wishlistError,
    isProcessingWishlist,
    shareWishlist,
  } = useContext(WishlistContext);
  const { user } = useContext(AuthContext);
  const navigate = useNavigate();

  const [shareUrl, setShareUrl] = useState(null);
  const [isSharing, setIsSharing] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!user) {
    navigate("/auth/login");
    return null;
  }

  const handleShare = async () => {
    setIsSharing(true);
    const result = await shareWishlist();
    if (result?.shareUrl) {
      setShareUrl(result.shareUrl);
    }
    setIsSharing(false);
  };

  const handleCopyLink = async () => {
    if (shareUrl) {
      try {
        await navigator.clipboard.writeText(shareUrl);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch {
        const textArea = document.createElement("textarea");
        textArea.value = shareUrl;
        textArea.style.position = "fixed";
        textArea.style.left = "-9999px";
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  };

  return (
    <>
      <Header />
      <section className="wishlist-page">
        <div className="wishlist-page__header">
          <h2 className="wishlist-page__title">
            My Wishlist
            {wishlistItems.length > 0 && (
              <span className="wishlist-page__count">
                ({wishlistItems.length} {wishlistItems.length === 1 ? "item" : "items"})
              </span>
            )}
          </h2>

          {wishlistItems.length > 0 && (
            <div className="wishlist-page__share">
              <button
                className="wishlist-page__share-btn"
                onClick={handleShare}
                disabled={isSharing}
              >
                <AiOutlineShareAlt size={18} />
                <span>{isSharing ? "Generating..." : "Share Wishlist"}</span>
              </button>
              {shareUrl && (
                <div className="wishlist-page__share-link">
                  <input
                    type="text"
                    value={shareUrl}
                    readOnly
                    className="wishlist-page__share-input"
                  />
                  <button
                    className="wishlist-page__copy-btn"
                    onClick={handleCopyLink}
                  >
                    {copied ? "Copied!" : "Copy"}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {isProcessingWishlist && <Loading />}
        {wishlistError && (
          <Info message="Unable to load your wishlist right now. Please try again later." />
        )}

        {!isProcessingWishlist && !wishlistError && wishlistItems.length === 0 && (
          <div className="wishlist-page__empty">
            <p>Your wishlist is empty.</p>
            <button onClick={() => navigate("/products/All")}>
              Browse Products
            </button>
          </div>
        )}

        {!isProcessingWishlist && !wishlistError && wishlistItems.length > 0 && (
          <div className="wishlist-page__grid">
            {wishlistItems.map((item) => (
              <WishlistCard key={item.productId} item={item} />
            ))}
          </div>
        )}
      </section>
      <Footer />
    </>
  );
}

export default WishlistPage;
