// Generated by SDLC Agent | 2026-04-08 | purely-wishlist-service-PURELY-23 | development
package com.purely.wishlist.security;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * DTO used to deserialize the auth-service token validation response.
 * Matches the structure returned by auth-service {@code /auth/isValidToken}.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserDetails {

    private String userId;

    private List<String> authorities;

}
